#!/usr/bin/env bun
/**
 * Generates `src/generated/navCatalog.ts` — the mobile nav drawer's catalog,
 * frozen at build time.
 *
 * Why this exists at all, in three moves:
 *
 *  1. Astro passed `categories` into `MobileNavIsland` as a build-time prop.
 *     That inlined the same 16.6 KB blob into all 1,039 pages — 17.3 MB, about
 *     a third of the built site. Designing the prop out is the single largest
 *     win in the Astro migration (ADR-031).
 *  2. The first attempt replaced the prop with a runtime `useGameData()` call.
 *     That deleted the HTML, but bought the bytes back as LATENCY (the drawer
 *     waited on the whole ~1.4 MB corpus) and then, when narrowed, as a
 *     `guides-*.js` + `catalog-categories-*.js` request on every page — which
 *     `e2e/bundle-budget.e2e.ts` explicitly forbids on leaf-schema pages.
 *  3. So do what DESIGN.md actually specified: the island imports its own
 *     static data in its OWN chunk. One shared copy, no ORM at runtime, no
 *     preload, no per-page duplication. The payload is small — the catalog
 *     serialises to ~9 KB — because it holds labels and hrefs, not entities.
 *
 * The output is COMMITTED, like `packages/salvageunion-reference/schemas/
 * *.schema.json`, so tests, typecheck and the dev server all work without a
 * prior build step. `__tests__/navCatalog.drift.test.ts` fails if the committed
 * file disagrees with what this script would write now, so it cannot rot.
 *
 * Run it with: bun ssg/genNavCatalog.ts   (also run by ssg/build.ts)
 */

import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

const OUTPUT = fileURLToPath(new URL('../src/generated/navCatalog.ts', import.meta.url))

/** Build the catalog exactly as `buildCatalogSections()` does at runtime. */
export async function renderNavCatalogModule(): Promise<string> {
  // Dynamic so this module can be imported for its types without paying the
  // ORM preload, and so `ssg/build.ts` can call it after its css-stub plugin
  // is registered (component-lib's barrel reaches `*.css`).
  const { SalvageUnionReference } = await import('salvageunion-reference')
  if (!SalvageUnionReference.isLoaded('chassis')) {
    await SalvageUnionReference.preload('all')
  }
  const { buildCatalogSections } = await import('component-lib')
  const sections = buildCatalogSections()

  if (sections.length === 0) {
    throw new Error('[nav-catalog] buildCatalogSections() returned nothing — refusing to write.')
  }

  return `// GENERATED by ssg/genNavCatalog.ts — DO NOT EDIT BY HAND.
// Regenerate with: bun ssg/genNavCatalog.ts
//
// The mobile nav drawer's catalog, frozen at build time so the island ships it
// in its own chunk instead of receiving it as per-page props (17.3 MB) or
// pulling the reference ORM at runtime (a data-chunk request on every page).
// See ssg/genNavCatalog.ts for the full rationale, and
// __tests__/navCatalog.drift.test.ts, which fails if this file goes stale.

import type { CatalogSection } from 'component-lib'

export const NAV_CATALOG: readonly CatalogSection[] = ${JSON.stringify(sections, null, 2)} as const
`
}

if (import.meta.main) {
  const source = await renderNavCatalogModule()
  await writeFile(OUTPUT, source, 'utf-8')
  process.stdout.write(`[nav-catalog] wrote ${OUTPUT} (${source.length} bytes)\n`)
}
