/**
 * intheunionnow.com — the ITUN SPA, on Workers (ADR-033), plus the one read
 * left of the retired snapshot API (ADR-036).
 *
 * ## The routing table, and why order is load-bearing
 *
 * Every rule has an incident behind it. Cloudflare cannot express
 * method-conditioned routing declaratively, so it is code, and
 * `__tests__/routing.test.ts` asserts each rule and each ordering constraint:
 *
 *   1. a retired URL           → 301 to what replaced it (the Share Snapshot
 *      screen, removed in #793; the per-entity detail pages collapsed into the
 *      live sheet; the snapshot unfurl image). The table is `./retiredRoutes.ts`.
 *      An installed PWA reaches this too: the service worker sends every
 *      navigation to the network first (`src/lib/sw/workbox.ts`).
 *   2. `/api/snapshots`        → **404**, every method. Publishing is retired
 *      (ADR-036); the endpoint is gone, not merely refusing a method.
 *   3. `/api/snapshots/:id`    → GET answers which entity the snapshot was taken
 *      of, so `/s/:id` can redirect to its live public sheet. Every other method
 *      is 405 — DELETE used to revoke, and nothing writes to the store any more.
 *   4. `/assets/*`             → a miss is **404**, never the SPA shell.
 *   5. a real file             → served as itself.
 *   6. a missing FILE          → **404**. Any path whose last segment contains
 *      a dot wanted a file; a client route in this app never does. This is what
 *      makes `/robots.txt` and `/favicon.ico` behave, and what stops every
 *      typo being an indexable soft-404 — see rule 6's own note below.
 *   7. everything else         → the SPA shell, 200.
 *
 * Every HTML document, whichever rule served it, leaves with
 * `SHELL_CACHE_CONTROL` — see the note on that constant.
 *
 * ## Rule 4 is the one that has already broken production
 *
 * Every hashed chunk a deploy rotates away is requested by exactly one
 * population: clients still running the previous build. Without this rule
 * those requests got `200 text/html`, the import rejected on MIME type,
 * and the `immutable` header pinned that HTML into the HTTP cache **for a year**
 * under the chunk's URL.
 *
 * Cloudflare's `not_found_handling: "single-page-application"` reintroduces
 * exactly that, which is why this Worker sets `"none"` and decides the fallback
 * itself. An honest 404 makes the failed import surface as `vite:preloadError`,
 * which `src/lib/chunkRecovery.ts` recovers from with a single reload.
 *
 * ## What went with snapshot publishing
 *
 * The edge rate limiter (it covered `POST /api/snapshots` and nothing else),
 * the per-snapshot shell metadata on `/s/:id`, and the rendered og:image behind
 * it. A retired link now unfurls with the sitewide defaults: advertising the
 * frozen build in its preview is exactly what was retired. The R2 objects are
 * kept untouched; this Worker only ever reads them.
 */

import type { ObservabilityEnv } from 'observability/cloudflare'
import { reportError, withObservability } from 'observability/cloudflare'
import { BASE_SECURITY_HEADERS } from 'observability/worker-http'
import { makeIdentityHandler } from '../lib/snapshot/handlers'
import { setSnapshotReporter } from '../lib/snapshot/report'
import type { R2BucketLike } from '../lib/snapshot/storage'
import { createR2Storage } from '../lib/snapshot/storage'
import { retiredRedirect } from './retiredRoutes'

export type Env = ObservabilityEnv & {
  /** Static assets (the built SPA). `not_found_handling` is "none" — see above. */
  ASSETS: { fetch(request: Request): Promise<Response> }
  /** The retired snapshot store — read, never written (ADR-036). */
  SNAPSHOTS: R2BucketLike
}

/** Serve the SPA shell for a client-side route. */
async function spaShell(request: Request, env: Env): Promise<Response> {
  const url = new URL(request.url)
  url.pathname = '/index.html'
  const shell = await env.ASSETS.fetch(new Request(url.toString(), { method: 'GET' }))
  // Re-wrap so the status is 200 for a client-side route rather than whatever
  // the asset lookup returned, and so this response is not confused with a hit
  // on a real file. (Its Cache-Control is forced on the way out — see
  // `SHELL_CACHE_CONTROL`.)
  return new Response(shell.body, { status: 200, headers: shell.headers })
}

/**
 * The `/*` block of `apps/itun/public/_headers`, in code.
 *
 * WHY IT HAS TO EXIST TWICE. Cloudflare's Static Assets docs are explicit that
 * `_headers` is **not applied to responses generated by Worker code**, and they
 * name `assets.run_worker_first` — which `wrangler.jsonc` sets — as a
 * configuration that triggers it. Every response this Worker builds itself is a
 * bare `new Response`: the retired-URL redirects, the 400/404/405s, the
 * snapshot handler, the SPA shell. All of them shipped with no CSP, no HSTS,
 * no `X-Frame-Options` and no `nosniff`.
 *
 * `apps/su-assets/src/worker.ts` has always done this (`COMMON_HEADERS` on
 * every response). itun had no equivalent, and its own `_headers` header
 * comment records that this exact class of gap already cost production once.
 *
 * Applied to asset responses too, deliberately. If `_headers` does reach them
 * this is an idempotent overwrite with identical values; if it does not, it is
 * the fix. Either way the browser gets them, which is the only thing that
 * counts. The post-deploy `smoke` job in `deploy-cloudflare.yml` asserts it
 * against production so the answer stops being a matter of reading docs.
 *
 * Keep in lockstep with `apps/itun/public/_headers`; `tools/check-observability.ts`
 * holds the CSP's Sentry ingest origin to the same value in both.
 */
const SECURITY_HEADERS: Record<string, string> = {
  // The six every Worker-served origin sends — shared with su-assets.
  ...BASE_SECURITY_HEADERS,
  'content-security-policy':
    "default-src 'self'; script-src 'self' https://storage.ko-fi.com; " +
    "style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; " +
    "connect-src 'self' https://*.ingest.de.sentry.io https://*.convex.cloud " +
    'wss://*.convex.cloud https://*.convex.site;',
}

/**
 * The Cache-Control on every HTML document this Worker sends: the SPA shell, on
 * whichever rule served it (rule 7 for a client route, rule 5 for `/` itself).
 *
 * It used to be inherited from whatever `ASSETS.fetch` returned — which is
 * correct today only because Workers Static Assets defaults to this exact value.
 * The `/*.html` rule in `public/_headers` cannot be the guarantee: Cloudflare does not
 * apply `_headers` to responses Worker code builds (the same gap
 * `SECURITY_HEADERS` closes), and rule 7 rebuilds every shell it serves. A
 * shell cached past a deploy names chunks that no longer exist, and the service
 * worker's network-first navigations (`src/lib/sw/workbox.ts`) are only as
 * fresh as this header lets the HTTP cache be.
 *
 * Kept identical to the `/*.html` block of `public/_headers`;
 * `__tests__/routing.test.ts` asserts the two agree.
 */
const SHELL_CACHE_CONTROL = 'public, max-age=0, must-revalidate'

/**
 * Copy a response, forcing the security headers on — and, for an HTML
 * document, `SHELL_CACHE_CONTROL`, which has the same `_headers` gap and so
 * gets the same once-on-the-way-out fix.
 *
 * `Response.redirect()` returns an immutable response, so the headers cannot be
 * mutated in place — rebuilding is not an optimisation choice here, it is the
 * only way. `response.body` is null for 204/304, which `new Response` accepts.
 */
function withSecurityHeaders(response: Response): Response {
  const headers = new Headers(response.headers)
  for (const [name, value] of Object.entries(SECURITY_HEADERS)) headers.set(name, value)
  if (headers.get('content-type')?.startsWith('text/html')) {
    headers.set('cache-control', SHELL_CACHE_CONTROL)
  }
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  })
}

/** @public Cloudflare Worker entrypoint — loaded by workerd, not imported. */
export default withObservability('itun', {
  // No `ctx`: nothing here defers work past the response any more (the
  // og:image cache write was the one thing that did).
  async fetch(request: Request, env: Env): Promise<Response> {
    // Wrapped once, here, rather than at each `return`. A per-return fix is how
    // the exit paths that existed came to ship bare.
    return withSecurityHeaders(await route(request, env))
  },
})

async function route(request: Request, env: Env): Promise<Response> {
  setSnapshotReporter((error, context) => {
    // Both, deliberately: Workers Logs is what `wrangler tail` shows during an
    // incident, Sentry is what alerts.
    console.error('[itun]', error, context ?? {})
    reportError(error, context)
  })

  const url = new URL(request.url)
  const path = url.pathname

  // 1. Retired URL. 301 rather than 302: none of these is coming back.
  //
  // This reaches installed PWAs too, because the service worker sends every
  // navigation to the network before its precache (`src/lib/sw/workbox.ts`).
  // See `./retiredRoutes.ts`.
  const retired = retiredRedirect(path)
  if (retired) return Response.redirect(`${url.origin}${retired}`, 301)

  // 2. The publish endpoint is gone (ADR-036). A 404 rather than a 405 is also
  //    what makes a still-open tab on an older build degrade honestly: its
  //    feature-detect read 405 as "available", and anything else as "publishing
  //    unavailable", so it stops offering a button that cannot work.
  if (path === '/api/snapshots' || path === '/api/snapshots/') {
    return new Response('Snapshot publishing has been retired', { status: 404 })
  }

  // 3. Which entity a snapshot was taken of. The handler answers 405 for
  //    everything that is not GET, and 400 for a malformed id before it reads.
  if (path.startsWith('/api/snapshots/')) {
    return makeIdentityHandler(createR2Storage(env.SNAPSHOTS))(request)
  }

  const assetResponse = await env.ASSETS.fetch(request)

  // 4. A build asset that does not exist must 404, NOT fall through to the
  //    SPA. See the header comment — this rule has already been a production
  //    incident once (#759).
  if (path.startsWith('/assets/')) {
    return assetResponse
  }

  // 5. A real file wins.
  if (assetResponse.status !== 404) {
    return assetResponse
  }

  // 6. A missing FILE is 404, not the SPA shell.
  //
  //    Rule 7 below is correct for client-side routes and wrong for
  //    everything else: `/robots.txt`, `/sitemap.xml` and `/favicon.ico` all
  //    answered `200 text/html` with the app in the body. A crawler asking
  //    for crawl rules got a web page; so did every typo, which makes the
  //    whole origin an infinite well of soft-404s to index.
  //
  //    A client route in this app never has a file extension — they are
  //    `/pilots/new`, `/sheet/$kind/$id`, `/games/$gameId`. So a dot in the
  //    last segment is a reliable signal that the request wanted a FILE, and
  //    a file that is not there is a 404. This is deliberately narrower than
  //    an allowlist of known filenames, which would go stale silently.
  //
  //    `/assets/*` is already handled above (rule 4) and stays there: it has
  //    its own production-incident history and should not depend on this.
  const lastSegment = path.slice(path.lastIndexOf('/') + 1)
  if (lastSegment.includes('.')) {
    return assetResponse
  }

  // 7. Anything else is a client-side route.
  return spaShell(request, env)
}
