/**
 * The security headers intheunionnow.com sends — the app's ONLY source of them.
 *
 * WHY THEY ARE SET IN CODE. Cloudflare's Static Assets docs are explicit that
 * `_headers` is **not applied to responses generated by Worker code**, and they
 * name `assets.run_worker_first` — which `wrangler.jsonc` sets — as a
 * configuration that triggers it. Every response the Worker builds itself is a
 * bare `new Response`: the retired-URL redirects, the 400/404/405s, the
 * snapshot handler, the SPA shell. Before this existed all of
 * them shipped with no CSP, no HSTS, no `X-Frame-Options` and no `nosniff`.
 *
 * `apps/su-assets/src/worker.ts` does the same (`COMMON_HEADERS` on every
 * response).
 *
 * Applied to asset responses too, because this is the only place the headers
 * are set: `public/_headers` carries Cache-Control and nothing else. The
 * post-deploy `smoke` job (`tools/smoke-production.sh`) asserts the CSP and
 * HSTS reach the browser from production.
 *
 * Two things read `ITUN_CSP` besides the Worker:
 *   - `tools/check-observability.ts` matches the literal below by regex and
 *     fails if `connect-src` stops admitting Sentry's ingest origin. Keep it
 *     ONE double-quoted string with no type annotation, or that gate fails
 *     with "declares no ITUN_CSP literal".
 *   - `__tests__/routing.test.ts` asserts it is the header that ships.
 */

import { BASE_SECURITY_HEADERS } from 'observability/worker-http'

/**
 * itun's Content-Security-Policy.
 *
 * `connect-src` MUST list Sentry's ingest origin or the browser blocks every
 * event before it leaves the page — a DSN alone is not enough, and that failure
 * is silent AND looks healthy (zero errors reported). `de`, not `us`: this org
 * is in Sentry's EU data region, and a DSN issued in one region under a CSP
 * written for the other is blocked just as silently. Kept in lockstep with
 * `SENTRY_INGEST_HOST` in `tools/check-observability.ts`, which fails CI if
 * this drifts. Wildcarded subdomain because the host encodes the Sentry org id.
 *
 * The Convex entries are load-bearing for the same reason and fail the same
 * silent way. The accounts client (ADR-030) opens a WebSocket to the deployment
 * for its reactive queries and POSTs mutations over HTTPS, and
 * `@convex-dev/auth` exchanges tokens against the deployment's `.site` origin.
 * Omit them and sign-in simply never completes, with no error surface.
 * Wildcarded per deployment name because production, a branch deploy and a
 * local `convex dev` differ. Both schemes are required — `wss:` does NOT
 * inherit from `https:`.
 *
 * `script-src` carries NO 'unsafe-inline': with it, an injected <script>
 * executes. The built `dist/index.html` contains zero inline scripts (Vite
 * bundles every module; the PWA registration is external). If a build ever
 * needs one, give that script a sha256 hash here, the way apps/srd does.
 * 'unsafe-inline' remains in `style-src`, deliberately — Tailwind and React
 * inline styles need it, and style injection is not script execution.
 *
 * `https://storage.ko-fi.com` is the Ko-fi widget script (`KofiButton`).
 */
export const ITUN_CSP =
  "default-src 'self'; script-src 'self' https://storage.ko-fi.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' https://*.ingest.de.sentry.io https://*.convex.cloud wss://*.convex.cloud https://*.convex.site;"

/** The six every Worker-served origin sends (shared with su-assets), plus the CSP. */
const SECURITY_HEADERS: Record<string, string> = {
  ...BASE_SECURITY_HEADERS,
  'content-security-policy': ITUN_CSP,
}

/**
 * The Cache-Control on every HTML document the Worker sends: the SPA shell, on
 * whichever rule served it (rule 7 for a client route, rule 5 for `/` itself).
 *
 * It used to be inherited from whatever `ASSETS.fetch` returned — which is
 * correct only because Workers Static Assets defaults to this exact value. The
 * `/*.html` rule in `public/_headers` cannot be the guarantee: Cloudflare does
 * not apply `_headers` to responses Worker code builds, and rule 7 rebuilds
 * every shell it serves. A shell cached past a deploy names chunks that no
 * longer exist, and the service worker's network-first navigations
 * (`src/lib/sw/workbox.ts`) are only as fresh as this header lets the HTTP
 * cache be.
 *
 * Kept identical to the `/*.html` block of `public/_headers`;
 * `__tests__/routing.test.ts` asserts the two agree.
 */
const SHELL_CACHE_CONTROL = 'public, max-age=0, must-revalidate'

/**
 * Copy a response, forcing the security headers on — and, for an HTML
 * document, `SHELL_CACHE_CONTROL`, which has the same `_headers` gap and so
 * gets the same once-on-the-way-out fix.
 *
 * `Response.redirect()` returns an immutable response, so the headers cannot be
 * mutated in place — rebuilding is not an optimisation choice here, it is the
 * only way. `response.body` is null for 204/304, which `new Response` accepts.
 */
export function withSecurityHeaders(response: Response): Response {
  const headers = new Headers(response.headers)
  for (const [name, value] of Object.entries(SECURITY_HEADERS)) headers.set(name, value)
  if (headers.get('content-type')?.startsWith('text/html')) {
    headers.set('cache-control', SHELL_CACHE_CONTROL)
  }
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  })
}
