/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PilotsNewRouteImport } from './routes/pilots/new'
import { Route as MechsNewRouteImport } from './routes/mechs/new'
import { Route as CrawlersNewRouteImport } from './routes/crawlers/new'
import { Route as MechsPatternsIndexRouteImport } from './routes/mechs/patterns/index'
import { Route as SheetKindIdRouteImport } from './routes/sheet/$kind/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotsNewRoute = PilotsNewRouteImport.update({
  id: '/pilots/new',
  path: '/pilots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MechsNewRoute = MechsNewRouteImport.update({
  id: '/mechs/new',
  path: '/mechs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CrawlersNewRoute = CrawlersNewRouteImport.update({
  id: '/crawlers/new',
  path: '/crawlers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MechsPatternsIndexRoute = MechsPatternsIndexRouteImport.update({
  id: '/mechs/patterns/',
  path: '/mechs/patterns/',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetKindIdRoute = SheetKindIdRouteImport.update({
  id: '/sheet/$kind/$id',
  path: '/sheet/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crawlers/new': typeof CrawlersNewRoute
  '/mechs/new': typeof MechsNewRoute
  '/pilots/new': typeof PilotsNewRoute
  '/sheet/$kind/$id': typeof SheetKindIdRoute
  '/mechs/patterns/': typeof MechsPatternsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crawlers/new': typeof CrawlersNewRoute
  '/mechs/new': typeof MechsNewRoute
  '/pilots/new': typeof PilotsNewRoute
  '/sheet/$kind/$id': typeof SheetKindIdRoute
  '/mechs/patterns': typeof MechsPatternsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crawlers/new': typeof CrawlersNewRoute
  '/mechs/new': typeof MechsNewRoute
  '/pilots/new': typeof PilotsNewRoute
  '/sheet/$kind/$id': typeof SheetKindIdRoute
  '/mechs/patterns/': typeof MechsPatternsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crawlers/new'
    | '/mechs/new'
    | '/pilots/new'
    | '/sheet/$kind/$id'
    | '/mechs/patterns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crawlers/new'
    | '/mechs/new'
    | '/pilots/new'
    | '/sheet/$kind/$id'
    | '/mechs/patterns'
  id:
    | '__root__'
    | '/'
    | '/crawlers/new'
    | '/mechs/new'
    | '/pilots/new'
    | '/sheet/$kind/$id'
    | '/mechs/patterns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrawlersNewRoute: typeof CrawlersNewRoute
  MechsNewRoute: typeof MechsNewRoute
  PilotsNewRoute: typeof PilotsNewRoute
  SheetKindIdRoute: typeof SheetKindIdRoute
  MechsPatternsIndexRoute: typeof MechsPatternsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilots/new': {
      id: '/pilots/new'
      path: '/pilots/new'
      fullPath: '/pilots/new'
      preLoaderRoute: typeof PilotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechs/new': {
      id: '/mechs/new'
      path: '/mechs/new'
      fullPath: '/mechs/new'
      preLoaderRoute: typeof MechsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crawlers/new': {
      id: '/crawlers/new'
      path: '/crawlers/new'
      fullPath: '/crawlers/new'
      preLoaderRoute: typeof CrawlersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechs/patterns/': {
      id: '/mechs/patterns/'
      path: '/mechs/patterns'
      fullPath: '/mechs/patterns/'
      preLoaderRoute: typeof MechsPatternsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheet/$kind/$id': {
      id: '/sheet/$kind/$id'
      path: '/sheet/$kind/$id'
      fullPath: '/sheet/$kind/$id'
      preLoaderRoute: typeof SheetKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrawlersNewRoute: CrawlersNewRoute,
  MechsNewRoute: MechsNewRoute,
  PilotsNewRoute: PilotsNewRoute,
  SheetKindIdRoute: SheetKindIdRoute,
  MechsPatternsIndexRoute: MechsPatternsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
