/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevRouteImport } from './routes/dev'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SIdRouteImport } from './routes/s/$id'
import { Route as PilotsNewRouteImport } from './routes/pilots/new'
import { Route as PilotsIdRouteImport } from './routes/pilots/$id'
import { Route as MechsNewRouteImport } from './routes/mechs/new'
import { Route as MechsIdRouteImport } from './routes/mechs/$id'
import { Route as CrawlersNewRouteImport } from './routes/crawlers/new'
import { Route as CrawlersIdRouteImport } from './routes/crawlers/$id'
import { Route as MechsPatternsIndexRouteImport } from './routes/mechs/patterns/index'
import { Route as SheetKindIdRouteImport } from './routes/sheet/$kind/$id'
import { Route as PilotsIdEditRouteImport } from './routes/pilots/$id_.edit'
import { Route as MechsIdEditRouteImport } from './routes/mechs/$id_.edit'
import { Route as CrawlersIdEditRouteImport } from './routes/crawlers/$id_.edit'
import { Route as SheetKindIdShareRouteImport } from './routes/sheet/$kind/$id_.share'

const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotsNewRoute = PilotsNewRouteImport.update({
  id: '/pilots/new',
  path: '/pilots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotsIdRoute = PilotsIdRouteImport.update({
  id: '/pilots/$id',
  path: '/pilots/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MechsNewRoute = MechsNewRouteImport.update({
  id: '/mechs/new',
  path: '/mechs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MechsIdRoute = MechsIdRouteImport.update({
  id: '/mechs/$id',
  path: '/mechs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CrawlersNewRoute = CrawlersNewRouteImport.update({
  id: '/crawlers/new',
  path: '/crawlers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CrawlersIdRoute = CrawlersIdRouteImport.update({
  id: '/crawlers/$id',
  path: '/crawlers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MechsPatternsIndexRoute = MechsPatternsIndexRouteImport.update({
  id: '/mechs/patterns/',
  path: '/mechs/patterns/',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetKindIdRoute = SheetKindIdRouteImport.update({
  id: '/sheet/$kind/$id',
  path: '/sheet/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotsIdEditRoute = PilotsIdEditRouteImport.update({
  id: '/pilots/$id_/edit',
  path: '/pilots/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const MechsIdEditRoute = MechsIdEditRouteImport.update({
  id: '/mechs/$id_/edit',
  path: '/mechs/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CrawlersIdEditRoute = CrawlersIdEditRouteImport.update({
  id: '/crawlers/$id_/edit',
  path: '/crawlers/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetKindIdShareRoute = SheetKindIdShareRouteImport.update({
  id: '/sheet/$kind/$id_/share',
  path: '/sheet/$kind/$id/share',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/crawlers/$id': typeof CrawlersIdRoute
  '/crawlers/new': typeof CrawlersNewRoute
  '/mechs/$id': typeof MechsIdRoute
  '/mechs/new': typeof MechsNewRoute
  '/pilots/$id': typeof PilotsIdRoute
  '/pilots/new': typeof PilotsNewRoute
  '/s/$id': typeof SIdRoute
  '/crawlers/$id/edit': typeof CrawlersIdEditRoute
  '/mechs/$id/edit': typeof MechsIdEditRoute
  '/pilots/$id/edit': typeof PilotsIdEditRoute
  '/sheet/$kind/$id': typeof SheetKindIdRoute
  '/mechs/patterns/': typeof MechsPatternsIndexRoute
  '/sheet/$kind/$id/share': typeof SheetKindIdShareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/crawlers/$id': typeof CrawlersIdRoute
  '/crawlers/new': typeof CrawlersNewRoute
  '/mechs/$id': typeof MechsIdRoute
  '/mechs/new': typeof MechsNewRoute
  '/pilots/$id': typeof PilotsIdRoute
  '/pilots/new': typeof PilotsNewRoute
  '/s/$id': typeof SIdRoute
  '/crawlers/$id/edit': typeof CrawlersIdEditRoute
  '/mechs/$id/edit': typeof MechsIdEditRoute
  '/pilots/$id/edit': typeof PilotsIdEditRoute
  '/sheet/$kind/$id': typeof SheetKindIdRoute
  '/mechs/patterns': typeof MechsPatternsIndexRoute
  '/sheet/$kind/$id/share': typeof SheetKindIdShareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/crawlers/$id': typeof CrawlersIdRoute
  '/crawlers/new': typeof CrawlersNewRoute
  '/mechs/$id': typeof MechsIdRoute
  '/mechs/new': typeof MechsNewRoute
  '/pilots/$id': typeof PilotsIdRoute
  '/pilots/new': typeof PilotsNewRoute
  '/s/$id': typeof SIdRoute
  '/crawlers/$id_/edit': typeof CrawlersIdEditRoute
  '/mechs/$id_/edit': typeof MechsIdEditRoute
  '/pilots/$id_/edit': typeof PilotsIdEditRoute
  '/sheet/$kind/$id': typeof SheetKindIdRoute
  '/mechs/patterns/': typeof MechsPatternsIndexRoute
  '/sheet/$kind/$id_/share': typeof SheetKindIdShareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev'
    | '/crawlers/$id'
    | '/crawlers/new'
    | '/mechs/$id'
    | '/mechs/new'
    | '/pilots/$id'
    | '/pilots/new'
    | '/s/$id'
    | '/crawlers/$id/edit'
    | '/mechs/$id/edit'
    | '/pilots/$id/edit'
    | '/sheet/$kind/$id'
    | '/mechs/patterns/'
    | '/sheet/$kind/$id/share'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev'
    | '/crawlers/$id'
    | '/crawlers/new'
    | '/mechs/$id'
    | '/mechs/new'
    | '/pilots/$id'
    | '/pilots/new'
    | '/s/$id'
    | '/crawlers/$id/edit'
    | '/mechs/$id/edit'
    | '/pilots/$id/edit'
    | '/sheet/$kind/$id'
    | '/mechs/patterns'
    | '/sheet/$kind/$id/share'
  id:
    | '__root__'
    | '/'
    | '/dev'
    | '/crawlers/$id'
    | '/crawlers/new'
    | '/mechs/$id'
    | '/mechs/new'
    | '/pilots/$id'
    | '/pilots/new'
    | '/s/$id'
    | '/crawlers/$id_/edit'
    | '/mechs/$id_/edit'
    | '/pilots/$id_/edit'
    | '/sheet/$kind/$id'
    | '/mechs/patterns/'
    | '/sheet/$kind/$id_/share'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevRoute: typeof DevRoute
  CrawlersIdRoute: typeof CrawlersIdRoute
  CrawlersNewRoute: typeof CrawlersNewRoute
  MechsIdRoute: typeof MechsIdRoute
  MechsNewRoute: typeof MechsNewRoute
  PilotsIdRoute: typeof PilotsIdRoute
  PilotsNewRoute: typeof PilotsNewRoute
  SIdRoute: typeof SIdRoute
  CrawlersIdEditRoute: typeof CrawlersIdEditRoute
  MechsIdEditRoute: typeof MechsIdEditRoute
  PilotsIdEditRoute: typeof PilotsIdEditRoute
  SheetKindIdRoute: typeof SheetKindIdRoute
  MechsPatternsIndexRoute: typeof MechsPatternsIndexRoute
  SheetKindIdShareRoute: typeof SheetKindIdShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilots/new': {
      id: '/pilots/new'
      path: '/pilots/new'
      fullPath: '/pilots/new'
      preLoaderRoute: typeof PilotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilots/$id': {
      id: '/pilots/$id'
      path: '/pilots/$id'
      fullPath: '/pilots/$id'
      preLoaderRoute: typeof PilotsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechs/new': {
      id: '/mechs/new'
      path: '/mechs/new'
      fullPath: '/mechs/new'
      preLoaderRoute: typeof MechsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechs/$id': {
      id: '/mechs/$id'
      path: '/mechs/$id'
      fullPath: '/mechs/$id'
      preLoaderRoute: typeof MechsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crawlers/new': {
      id: '/crawlers/new'
      path: '/crawlers/new'
      fullPath: '/crawlers/new'
      preLoaderRoute: typeof CrawlersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crawlers/$id': {
      id: '/crawlers/$id'
      path: '/crawlers/$id'
      fullPath: '/crawlers/$id'
      preLoaderRoute: typeof CrawlersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechs/patterns/': {
      id: '/mechs/patterns/'
      path: '/mechs/patterns'
      fullPath: '/mechs/patterns/'
      preLoaderRoute: typeof MechsPatternsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheet/$kind/$id': {
      id: '/sheet/$kind/$id'
      path: '/sheet/$kind/$id'
      fullPath: '/sheet/$kind/$id'
      preLoaderRoute: typeof SheetKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilots/$id_/edit': {
      id: '/pilots/$id_/edit'
      path: '/pilots/$id/edit'
      fullPath: '/pilots/$id/edit'
      preLoaderRoute: typeof PilotsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechs/$id_/edit': {
      id: '/mechs/$id_/edit'
      path: '/mechs/$id/edit'
      fullPath: '/mechs/$id/edit'
      preLoaderRoute: typeof MechsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crawlers/$id_/edit': {
      id: '/crawlers/$id_/edit'
      path: '/crawlers/$id/edit'
      fullPath: '/crawlers/$id/edit'
      preLoaderRoute: typeof CrawlersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheet/$kind/$id_/share': {
      id: '/sheet/$kind/$id_/share'
      path: '/sheet/$kind/$id/share'
      fullPath: '/sheet/$kind/$id/share'
      preLoaderRoute: typeof SheetKindIdShareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevRoute: DevRoute,
  CrawlersIdRoute: CrawlersIdRoute,
  CrawlersNewRoute: CrawlersNewRoute,
  MechsIdRoute: MechsIdRoute,
  MechsNewRoute: MechsNewRoute,
  PilotsIdRoute: PilotsIdRoute,
  PilotsNewRoute: PilotsNewRoute,
  SIdRoute: SIdRoute,
  CrawlersIdEditRoute: CrawlersIdEditRoute,
  MechsIdEditRoute: MechsIdEditRoute,
  PilotsIdEditRoute: PilotsIdEditRoute,
  SheetKindIdRoute: SheetKindIdRoute,
  MechsPatternsIndexRoute: MechsPatternsIndexRoute,
  SheetKindIdShareRoute: SheetKindIdShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
