/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedPatternsNewRouteImport } from './routes/_authenticated/patterns/new'
import { Route as AuthenticatedPatternsPatternIdRouteImport } from './routes/_authenticated/patterns/$patternId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPatternsNewRoute =
  AuthenticatedPatternsNewRouteImport.update({
    id: '/patterns/new',
    path: '/patterns/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatternsPatternIdRoute =
  AuthenticatedPatternsPatternIdRouteImport.update({
    id: '/patterns/$patternId',
    path: '/patterns/$patternId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/patterns/$patternId': typeof AuthenticatedPatternsPatternIdRoute
  '/patterns/new': typeof AuthenticatedPatternsNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/patterns/$patternId': typeof AuthenticatedPatternsPatternIdRoute
  '/patterns/new': typeof AuthenticatedPatternsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/patterns/$patternId': typeof AuthenticatedPatternsPatternIdRoute
  '/_authenticated/patterns/new': typeof AuthenticatedPatternsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/patterns/$patternId'
    | '/patterns/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/auth/callback'
    | '/'
    | '/patterns/$patternId'
    | '/patterns/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/patterns/$patternId'
    | '/_authenticated/patterns/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/patterns/new': {
      id: '/_authenticated/patterns/new'
      path: '/patterns/new'
      fullPath: '/patterns/new'
      preLoaderRoute: typeof AuthenticatedPatternsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patterns/$patternId': {
      id: '/_authenticated/patterns/$patternId'
      path: '/patterns/$patternId'
      fullPath: '/patterns/$patternId'
      preLoaderRoute: typeof AuthenticatedPatternsPatternIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPatternsPatternIdRoute: typeof AuthenticatedPatternsPatternIdRoute
  AuthenticatedPatternsNewRoute: typeof AuthenticatedPatternsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPatternsPatternIdRoute: AuthenticatedPatternsPatternIdRoute,
  AuthenticatedPatternsNewRoute: AuthenticatedPatternsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
