/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RandsumRouteImport } from './routes/randsum'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchemaSchemaIdIndexRouteImport } from './routes/schema/$schemaId/index'
import { Route as SchemaSchemaIdItemItemIdRouteImport } from './routes/schema/$schemaId/item/$itemId'

const RandsumRoute = RandsumRouteImport.update({
  id: '/randsum',
  path: '/randsum',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaSchemaIdIndexRoute = SchemaSchemaIdIndexRouteImport.update({
  id: '/schema/$schemaId/',
  path: '/schema/$schemaId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaSchemaIdItemItemIdRoute =
  SchemaSchemaIdItemItemIdRouteImport.update({
    id: '/schema/$schemaId/item/$itemId',
    path: '/schema/$schemaId/item/$itemId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/randsum': typeof RandsumRoute
  '/schema/$schemaId/': typeof SchemaSchemaIdIndexRoute
  '/schema/$schemaId/item/$itemId': typeof SchemaSchemaIdItemItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/randsum': typeof RandsumRoute
  '/schema/$schemaId': typeof SchemaSchemaIdIndexRoute
  '/schema/$schemaId/item/$itemId': typeof SchemaSchemaIdItemItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/randsum': typeof RandsumRoute
  '/schema/$schemaId/': typeof SchemaSchemaIdIndexRoute
  '/schema/$schemaId/item/$itemId': typeof SchemaSchemaIdItemItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/randsum'
    | '/schema/$schemaId/'
    | '/schema/$schemaId/item/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/randsum'
    | '/schema/$schemaId'
    | '/schema/$schemaId/item/$itemId'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/randsum'
    | '/schema/$schemaId/'
    | '/schema/$schemaId/item/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  RandsumRoute: typeof RandsumRoute
  SchemaSchemaIdIndexRoute: typeof SchemaSchemaIdIndexRoute
  SchemaSchemaIdItemItemIdRoute: typeof SchemaSchemaIdItemItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/randsum': {
      id: '/randsum'
      path: '/randsum'
      fullPath: '/randsum'
      preLoaderRoute: typeof RandsumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema/$schemaId/': {
      id: '/schema/$schemaId/'
      path: '/schema/$schemaId'
      fullPath: '/schema/$schemaId/'
      preLoaderRoute: typeof SchemaSchemaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema/$schemaId/item/$itemId': {
      id: '/schema/$schemaId/item/$itemId'
      path: '/schema/$schemaId/item/$itemId'
      fullPath: '/schema/$schemaId/item/$itemId'
      preLoaderRoute: typeof SchemaSchemaIdItemItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  RandsumRoute: RandsumRoute,
  SchemaSchemaIdIndexRoute: SchemaSchemaIdIndexRoute,
  SchemaSchemaIdItemItemIdRoute: SchemaSchemaIdItemItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
