// PUBLIC API SURFACE REPORT — generated by tools/generateApiReport.ts. Do not edit.
// Rooted at the code entry points in package.json#exports:
//   lib/index.ts
//   lib/rules/index.ts
//   lib/schemaDefinitions.ts
//   lib/testing.ts
//   lib/zod.ts
// Every section below is a declaration file reachable from one of those roots,
// except the Zod schema declarations under lib/schemas/ (gated by schemas/*.schema.json).
// === lib/BaseModel.d.ts ===
export type ModelWithMetadata<T> = BaseModel<T> & {
    readonly schemaName: string;
    readonly displayName: string;
};
export declare class BaseModel<T> {
    protected data: (T & {
        schemaName: string;
    })[];
    protected idMap: Map<string, T & {
        schemaName: string;
    }>;
    protected nameMap: Map<string, T & {
        schemaName: string;
    }> | null;
    protected slugMap: Map<string, T & {
        schemaName: string;
    }> | null;
    protected _schemaName: string;
    protected _displayName: string;
    constructor(data: T[], schemaName: string, displayName: string);
    all(): (T & {
        schemaName: string;
    })[];
    find(predicate: (item: T) => boolean): (T & {
        schemaName: string;
    }) | undefined;
    findAll(predicate: (item: T) => boolean): (T & {
        schemaName: string;
    })[];
    getById(id: string): (T & {
        schemaName: string;
    }) | undefined;
    getByName(name: string): (T & {
        schemaName: string;
    }) | undefined;
    getBySlug(slug: string): (T & {
        schemaName: string;
    }) | undefined;
    private buildKeyIndex;
}
//# sourceMappingURL=BaseModel.d.ts.map
// === lib/LazyModel.d.ts ===
import { BaseModel } from './BaseModel.js';
export declare class LazyModel<T> extends BaseModel<T> {
    private readonly _schemaIdForLazy;
    private _backing;
    readonly schemaName: string;
    readonly displayName: string;
    constructor(schemaId: string, _propName: string, displayNameValue: string);
    _install(backing: BaseModel<T>): void;
    _reset(): void;
    private _loadedBacking;
    all(): (T & {
        schemaName: string;
    })[];
    find(predicate: (item: T) => boolean): (T & {
        schemaName: string;
    }) | undefined;
    findAll(predicate: (item: T) => boolean): (T & {
        schemaName: string;
    })[];
    getById(id: string): (T & {
        schemaName: string;
    }) | undefined;
    getByName(name: string): (T & {
        schemaName: string;
    }) | undefined;
    getBySlug(slug: string): (T & {
        schemaName: string;
    }) | undefined;
}
//# sourceMappingURL=LazyModel.d.ts.map
// === lib/ModelFactory.d.ts ===
import { BaseModel } from './BaseModel.js';
import { schemaDisplayNames } from './generated/modelFactoryRegistry.generated.js';
import { toPascalCase } from './naming.js';
export { schemaDisplayNames, toPascalCase };
export type LoadOptions = {
    validate?: boolean;
};
export declare function isSchemaLoaded(schemaId: string): boolean;
export declare function loadSchemas(schemas: string[] | 'all', options?: LoadOptions): Promise<void>;
export declare function getLoadedModel(schemaId: string, propertyName: string): BaseModel<unknown>;
export declare function getLoadedModelBySchemaId(schemaId: string): BaseModel<unknown> | undefined;
export declare function resetLoadStateForTesting(): void;
export declare function getDataMaps(): {
    dataMap: Record<string, unknown[]>;
};
export declare const _registryKeySets: {
    dataLoaders: string[];
};
export type EnhancedSchemaMetadata = {
    id: string;
    title: string;
    description: string;
    comment?: string;
    dataFile: string;
    schemaFile: string;
    itemCount: number;
    requiredFields: string[];
    displayName: string;
    displayNamePlural: string;
    meta?: boolean;
};
export declare function getSchemaCatalog(): {
    $schema: string;
    title: string;
    description: string;
    generated: string;
    schemas: EnhancedSchemaMetadata[];
};
//# sourceMappingURL=ModelFactory.d.ts.map
// === lib/actionResolution.d.ts ===
import type { SURefMetaAction, SURefMetaEntity, SURefObjectChoice, SURefObjectTrait } from './schemas/index.js';
export declare function invalidateActionMap(): void;
export declare function extractActions(entity: SURefMetaEntity): SURefMetaAction[] | undefined;
export declare function extractVisibleActions(entity: SURefMetaEntity): SURefMetaAction[] | undefined;
export declare function getChassisAbilities(entity: SURefMetaEntity): SURefMetaAction[] | undefined;
type DamageValue = {
    damageType: string;
    amount: number | string;
};
export declare function getActionType(entity: SURefMetaEntity): string | undefined;
export declare function getRange(entity: SURefMetaEntity): string[] | undefined;
export declare function getDamage(entity: SURefMetaEntity): DamageValue | undefined;
export declare function getTraits(entity: SURefMetaEntity): SURefObjectTrait[] | undefined;
export declare function getChoices(entity: SURefMetaEntity): SURefObjectChoice[] | undefined;
export {};
//# sourceMappingURL=actionResolution.d.ts.map
// === lib/assets.d.ts ===
import type { SURefMetaEntity } from './schemas/index.js';
export declare const ASSET_BASE_URL = "https://assets.salvageunion.io";
export declare function getAssetUrl(entity: SURefMetaEntity): string | undefined;
export declare const SRD_SITE_URL = "https://salvageunion.io";
export declare function srdEntityPath(schemaName: string, slug: string): string;
export declare function srdSchemaPath(schemaName: string): string;
export declare function srdSchemaUrl(schemaName: string): string;
export declare function srdEntityUrl(schemaName: string, slug: string): string;
//# sourceMappingURL=assets.d.ts.map
// === lib/contentBlockHelpers.d.ts ===
import type { SURefObjectContentBlock, SURefObjectDataValue } from './schemas/index.js';
export declare function replaceChassisPlaceholder(text: string | undefined, chassisName?: string): string;
export declare function parseContentBlockString(block: SURefObjectContentBlock, chassisName?: string): string;
export declare function resolveDataValueForTechLevel(dv: SURefObjectDataValue, effectiveTechLevel: number | undefined): {
    value: number | string | undefined;
    scaled: boolean;
};
//# sourceMappingURL=contentBlockHelpers.d.ts.map
// === lib/entityFields.d.ts ===
import type { SURefMetaEntity, SURefObjectGrant } from './schemas/index.js';
export declare function getTechLevel(entity: SURefMetaEntity): number | 'B' | 'N' | undefined;
export declare function getTechLevelNumber(entity: SURefMetaEntity): number | undefined;
export declare function getSalvageValue(entity: SURefMetaEntity): number | undefined;
export declare function getSlotsRequired(entity: SURefMetaEntity): number | undefined;
export declare function getPageReference(entity: SURefMetaEntity): number | undefined;
export declare function getStructurePoints(entity: SURefMetaEntity): number | undefined;
export declare function getEnergyPoints(entity: SURefMetaEntity): number | undefined;
export declare function getHeatCapacity(entity: SURefMetaEntity): number | undefined;
export declare function getSystemSlots(entity: SURefMetaEntity): number | undefined;
export declare function getModuleSlots(entity: SURefMetaEntity): number | undefined;
export declare function getCargoCapacity(entity: SURefMetaEntity): number | undefined;
export declare function getUpkeepCost(entity: SURefMetaEntity): number | undefined;
export declare function getUpgradeCost(entity: SURefMetaEntity): number | undefined;
export declare function getHitPoints(entity: SURefMetaEntity): number | undefined;
export declare function getBlackMarket(entity: SURefMetaEntity): boolean | undefined;
export declare function getContent(entity: SURefMetaEntity): unknown | undefined;
export declare function getName(entity: SURefMetaEntity): string | undefined;
export declare function getSource(entity: SURefMetaEntity): string | undefined;
export declare function getBooklet(entity: SURefMetaEntity): string | undefined;
export declare function getTree(entity: SURefMetaEntity): unknown | undefined;
export declare function getBioSalvageValue(entity: SURefMetaEntity): number | undefined;
export declare function getReferenceEntityName(entity: SURefMetaEntity): string | undefined;
export declare function getDescription(entity: SURefMetaEntity): string | undefined;
export declare function getGrants(entity: SURefMetaEntity): SURefObjectGrant[] | undefined;
//# sourceMappingURL=entityFields.d.ts.map
// === lib/entityGuards.d.ts ===
import type { SURefAbility, SURefClass, SURefEntity, SURefKeyword, SURefMetaEntity, SURefObjectAdvancedClass } from './schemas/index.js';
export declare function isEntityData<T extends object>(data: T): data is T & SURefEntity & {
    id: string;
    name: string;
    source: string;
    page: number;
};
export declare function isAbility(entity: SURefMetaEntity | null | undefined): entity is SURefAbility;
export declare function isKeyword(entity: SURefMetaEntity): entity is SURefKeyword;
export declare function isCoreClass(entity: SURefMetaEntity): entity is SURefClass & {
    coreTrees: string[];
};
export declare function isBaseAdvancedClass(entity: SURefMetaEntity): entity is SURefObjectAdvancedClass;
//# sourceMappingURL=entityGuards.d.ts.map
// === lib/generated/entityTypes.generated.d.ts ===
import type { z } from '../zod.js';
import type { AbilitySchema, AbilityTreeRequirementSchema, MetaActionSchema, ChassisSchema, ClassSchema, CrawlerBaySchema, CrawlerTechLevelSchema, CrawlerSchema, CreatureSchema, DistanceSchema, DroneSchema, EquipmentSchema, FactionSchema, GuideSchema, KeywordSchema, MeldSchema, ModuleSchema, NPCSchema, RollTableSchema, SquadSchema, SystemSchema, BioTitanSchema, TraitEntitySchema, VehicleSchema, SourceEntitySchema, TechLevelEntitySchema, CatalogCategorySchema } from '../schemas/entities.js';
export type SURefAbility = z.infer<typeof AbilitySchema>;
export type SURefMetaAbilityTreeRequirement = z.infer<typeof AbilityTreeRequirementSchema>;
export type SURefMetaAction = z.infer<typeof MetaActionSchema>;
export type SURefChassis = z.infer<typeof ChassisSchema>;
export type SURefClass = z.infer<typeof ClassSchema>;
export type SURefCrawlerBay = z.infer<typeof CrawlerBaySchema>;
export type SURefMetaCrawlerTechLevel = z.infer<typeof CrawlerTechLevelSchema>;
export type SURefCrawler = z.infer<typeof CrawlerSchema>;
export type SURefCreature = z.infer<typeof CreatureSchema>;
export type SURefDistance = z.infer<typeof DistanceSchema>;
export type SURefDrone = z.infer<typeof DroneSchema>;
export type SURefEquipment = z.infer<typeof EquipmentSchema>;
export type SURefFaction = z.infer<typeof FactionSchema>;
export type SURefGuide = z.infer<typeof GuideSchema>;
export type SURefKeyword = z.infer<typeof KeywordSchema>;
export type SURefMeld = z.infer<typeof MeldSchema>;
export type SURefModule = z.infer<typeof ModuleSchema>;
export type SURefNPC = z.infer<typeof NPCSchema>;
export type SURefRollTable = z.infer<typeof RollTableSchema>;
export type SURefSquad = z.infer<typeof SquadSchema>;
export type SURefSystem = z.infer<typeof SystemSchema>;
export type SURefBioTitan = z.infer<typeof BioTitanSchema>;
export type SURefTrait = z.infer<typeof TraitEntitySchema>;
export type SURefVehicle = z.infer<typeof VehicleSchema>;
export type SURefSource = z.infer<typeof SourceEntitySchema>;
export type SURefTechLevel = z.infer<typeof TechLevelEntitySchema>;
export type SURefCatalogCategory = z.infer<typeof CatalogCategorySchema>;
export type SURefEntity = SURefAbility | SURefChassis | SURefClass | SURefCrawlerBay | SURefCrawler | SURefCreature | SURefDistance | SURefDrone | SURefEquipment | SURefFaction | SURefGuide | SURefKeyword | SURefMeld | SURefModule | SURefNPC | SURefRollTable | SURefSquad | SURefSystem | SURefBioTitan | SURefTrait | SURefVehicle | SURefSource | SURefTechLevel;
export type SURefMetaEntity = SURefAbility | SURefMetaAbilityTreeRequirement | SURefMetaAction | SURefChassis | SURefClass | SURefCrawlerBay | SURefMetaCrawlerTechLevel | SURefCrawler | SURefCreature | SURefDistance | SURefDrone | SURefEquipment | SURefFaction | SURefGuide | SURefKeyword | SURefMeld | SURefModule | SURefNPC | SURefRollTable | SURefSquad | SURefSystem | SURefBioTitan | SURefTrait | SURefVehicle | SURefSource | SURefTechLevel;
//# sourceMappingURL=entityTypes.generated.d.ts.map
// === lib/generated/modelFactoryRegistry.generated.d.ts ===
export declare const dataLoaders: Record<string, () => Promise<unknown[]>>;
export declare const schemaDisplayNames: Record<string, {
    singular: string;
    plural: string;
}>;
//# sourceMappingURL=modelFactoryRegistry.generated.d.ts.map
// === lib/generated/schemaRegistry.generated.d.ts ===
import { LazyModel } from '../LazyModel.js';
import type { SURefAbility, SURefMetaAbilityTreeRequirement, SURefMetaAction, SURefChassis, SURefClass, SURefCrawlerBay, SURefMetaCrawlerTechLevel, SURefCrawler, SURefCreature, SURefDistance, SURefDrone, SURefEquipment, SURefFaction, SURefGuide, SURefKeyword, SURefMeld, SURefModule, SURefNPC, SURefRollTable, SURefSquad, SURefSystem, SURefBioTitan, SURefTrait, SURefVehicle, SURefSource, SURefTechLevel, SURefCatalogCategory } from '../schemas/index.js';
export type SchemaToEntityMap = {
    abilities: SURefAbility;
    'ability-tree-requirements': SURefMetaAbilityTreeRequirement;
    actions: SURefMetaAction;
    chassis: SURefChassis;
    classes: SURefClass;
    'crawler-bays': SURefCrawlerBay;
    'crawler-tech-levels': SURefMetaCrawlerTechLevel;
    crawlers: SURefCrawler;
    creatures: SURefCreature;
    distances: SURefDistance;
    drones: SURefDrone;
    equipment: SURefEquipment;
    factions: SURefFaction;
    guides: SURefGuide;
    keywords: SURefKeyword;
    meld: SURefMeld;
    modules: SURefModule;
    npcs: SURefNPC;
    'roll-tables': SURefRollTable;
    squads: SURefSquad;
    systems: SURefSystem;
    'bio-titans': SURefBioTitan;
    traits: SURefTrait;
    vehicles: SURefVehicle;
    sources: SURefSource;
    'tech-levels': SURefTechLevel;
    'catalog-categories': SURefCatalogCategory;
};
export type EntitySchemaName = keyof SchemaToEntityMap;
export declare const lazyModelMap: {
    readonly [K in keyof SchemaToEntityMap]: LazyModel<SchemaToEntityMap[K]>;
};
export declare const SCHEMA_REGISTRY: {
    readonly abilities: {
        readonly model: 'Abilities';
        readonly display: 'Ability';
    };
    readonly 'ability-tree-requirements': {
        readonly model: 'AbilityTreeRequirements';
        readonly display: 'Ability Tree Requirement';
    };
    readonly actions: {
        readonly model: 'Actions';
        readonly display: 'Action';
    };
    readonly chassis: {
        readonly model: 'Chassis';
        readonly display: 'Chassis';
    };
    readonly classes: {
        readonly model: 'Classes';
        readonly display: 'Class';
    };
    readonly 'crawler-bays': {
        readonly model: 'CrawlerBays';
        readonly display: 'Crawler Bay';
    };
    readonly 'crawler-tech-levels': {
        readonly model: 'CrawlerTechLevels';
        readonly display: 'Crawler Tech Level';
    };
    readonly crawlers: {
        readonly model: 'Crawlers';
        readonly display: 'Crawler';
    };
    readonly creatures: {
        readonly model: 'Creatures';
        readonly display: 'Creature';
    };
    readonly distances: {
        readonly model: 'Distances';
        readonly display: 'Distance';
    };
    readonly drones: {
        readonly model: 'Drones';
        readonly display: 'Drone';
    };
    readonly equipment: {
        readonly model: 'Equipment';
        readonly display: 'Equipment';
    };
    readonly factions: {
        readonly model: 'Factions';
        readonly display: 'Faction';
    };
    readonly guides: {
        readonly model: 'Guides';
        readonly display: 'Guide';
    };
    readonly keywords: {
        readonly model: 'Keywords';
        readonly display: 'Keyword';
    };
    readonly meld: {
        readonly model: 'Meld';
        readonly display: 'Meld';
    };
    readonly modules: {
        readonly model: 'Modules';
        readonly display: 'Module';
    };
    readonly npcs: {
        readonly model: 'NPCs';
        readonly display: 'NPC';
    };
    readonly 'roll-tables': {
        readonly model: 'RollTables';
        readonly display: 'Roll Table';
    };
    readonly squads: {
        readonly model: 'Squads';
        readonly display: 'Squad';
    };
    readonly systems: {
        readonly model: 'Systems';
        readonly display: 'System';
    };
    readonly 'bio-titans': {
        readonly model: 'BioTitans';
        readonly display: 'Bio-Titan';
    };
    readonly traits: {
        readonly model: 'Traits';
        readonly display: 'Trait';
    };
    readonly vehicles: {
        readonly model: 'Vehicles';
        readonly display: 'Vehicle';
    };
    readonly sources: {
        readonly model: 'Sources';
        readonly display: 'Source';
    };
    readonly 'tech-levels': {
        readonly model: 'TechLevels';
        readonly display: 'Tech Level';
    };
    readonly 'catalog-categories': {
        readonly model: 'CatalogCategories';
        readonly display: 'Catalog Category';
        readonly entity: false;
    };
};
//# sourceMappingURL=schemaRegistry.generated.d.ts.map
// === lib/generated/zodSchemaMap.generated.d.ts ===
import type { z } from '../zod.js';
export declare const zodSchemaMap: Record<string, z.ZodType<unknown>>;
//# sourceMappingURL=zodSchemaMap.generated.d.ts.map
// === lib/helpers.d.ts ===
import type { ModelWithMetadata } from './BaseModel.js';
import type { EnhancedSchemaMetadata } from './ModelFactory.js';
import type { SURefEntity, SURefEnumSchemaName, SURefObjectAdvancedClass } from './schemas/index.js';
import type { TableRow } from './utils/tableRows.js';
export declare function getDisplayName(schemaName: SURefEnumSchemaName): string;
export declare function normalizeSchemaName(schemaName: string): SURefEnumSchemaName;
export declare function getModel(schemaName: string | SURefEnumSchemaName): ModelWithMetadata<SURefEntity> | undefined;
export declare function resolveGrantedEntities(entity: SURefEntity): SURefEntity[];
export declare function getHybridClasses(): (SURefObjectAdvancedClass & {
    schemaName: string;
})[];
export declare function resolveActivationCurrency(schemaName: SURefEnumSchemaName | 'actions' | undefined, variable?: boolean): 'AP' | 'EP' | 'XP';
export declare function getEntitySchemas(): EnhancedSchemaMetadata[];
export declare function techLevelRank(techLevel: number | 'B' | 'N' | undefined): number;
export declare function byTechLevelThenName(a: {
    techLevel?: number | 'B' | 'N';
    name: string;
}, b: {
    techLevel?: number | 'B' | 'N';
    name: string;
}): number;
export declare function getUniqueTechLevels(entities: SURefEntity[]): (number | 'B' | 'N')[];
export declare function getUniqueSources(entities: SURefEntity[]): string[];
export declare function getUniqueTrees(entities: SURefEntity[]): string[];
export type ReferenceEntityData = {
    id: string;
    name: string;
    slug: string;
    description: string | undefined;
    source: string | undefined;
    page: number | undefined;
    techLevel: number | 'B' | 'N' | undefined;
    assetUrl: string | undefined;
};
export declare function getReferenceEntityData(entity: SURefEntity): ReferenceEntityData;
export type StaticEntitySummary = {
    name: string;
    description: string | undefined;
    source: string | undefined;
    page: number | undefined;
    techLevel: number | 'B' | 'N' | undefined;
    contentParagraphs: string[];
    stats: {
        label: string;
        value: string | number;
    }[];
    traits: string[];
    sections: {
        name: string;
        paragraphs: string[];
    }[];
    table: TableRow[];
};
export declare function extractStaticEntitySummary(entity: SURefEntity): StaticEntitySummary;
//# sourceMappingURL=helpers.d.ts.map
// === lib/index.d.ts ===
import type { ModelWithMetadata } from './BaseModel.js';
import type { EntitySchemaName, SchemaToEntityMap } from './generated/schemaRegistry.generated.js';
import { SCHEMA_REGISTRY } from './generated/schemaRegistry.generated.js';
import type { LoadOptions } from './ModelFactory.js';
import type { SURefEntity, SURefEnumSchemaName, SURefMetaAction, SURefMetaEntity } from './schemas/index.js';
export { extractVisibleActions, getChassisAbilities, getChoices, getTraits, } from './actionResolution.js';
export { getAssetUrl, SRD_SITE_URL, srdEntityPath, srdEntityUrl, srdSchemaPath, srdSchemaUrl, } from './assets.js';
export { parseContentBlockString, replaceChassisPlaceholder, resolveDataValueForTechLevel, } from './contentBlockHelpers.js';
export { getBioSalvageValue, getBlackMarket, getBooklet, getCargoCapacity, getEnergyPoints, getHeatCapacity, getHitPoints, getModuleSlots, getName, getPageReference, getReferenceEntityName, getSalvageValue, getSlotsRequired, getSource, getStructurePoints, getSystemSlots, getTechLevel, getTechLevelNumber, getTree, getUpgradeCost, getUpkeepCost, } from './entityFields.js';
export { isAbility, isBaseAdvancedClass, isCoreClass, isEntityData, isKeyword, } from './entityGuards.js';
export type * from './generated/entityTypes.generated.js';
export { byTechLevelThenName, extractStaticEntitySummary, getDisplayName, getEntitySchemas, getHybridClasses, getModel, getReferenceEntityData, getUniqueSources, getUniqueTechLevels, getUniqueTrees, resolveActivationCurrency, resolveGrantedEntities, type StaticEntitySummary, techLevelRank, } from './helpers.js';
export { getInventorySlots } from './inventorySlots.js';
export { type EnhancedSchemaMetadata, getDataMaps, getSchemaCatalog } from './ModelFactory.js';
export { nameToSlug } from './nameToSlug.js';
export { getPatterns, normalizePatternName, visiblePatterns } from './patterns.js';
export { type ChoiceSelections, resolveChoiceView } from './resolveChoiceView.js';
export { type RollOnTableOutcome, rollOnTable } from './rollOnTable.js';
export type { SURefEnumSchemaName, SURefObjectBonusPerTechLevel, SURefObjectChoice, SURefObjectContent, SURefObjectContentBlock, SURefObjectDamage, SURefObjectDataValue, SURefObjectGuideStep, SURefObjectPattern, SURefObjectPatternSystemModule, SURefObjectTable, SURefObjectTableContent, SURefObjectTrait, } from './schemas/index.js';
export { extractContentText, isSchemaName, type SearchOptions, type SearchResult, search, searchIn, } from './search.js';
export { matchSearchTokens, scoreSearchMatch, searchNameWords, tokenizeSearchQuery, } from './searchRanking.js';
export { findEntityBySlug, getEntitySlug } from './slug.js';
export { parseTraitReferences, replaceTraitReferences } from './traitText.js';
export { resultForColumnsTable, resultForTable } from './utils/resultForTable.js';
import type { SearchOptions, SearchResult } from './search.js';
export type { EntitySchemaName, SchemaToEntityMap };
export declare const EntitySchemaNames: Set<keyof SchemaToEntityMap>;
export declare const SchemaToModelMap: { readonly [K in keyof typeof SCHEMA_REGISTRY]: (typeof SCHEMA_REGISTRY)[K]['model']; };
export declare const SchemaToDisplayName: { readonly [K in keyof typeof SCHEMA_REGISTRY]: (typeof SCHEMA_REGISTRY)[K]['display']; };
export declare class SalvageUnionReference {
    static Abilities: ModelWithMetadata<SchemaToEntityMap['abilities']>;
    static AbilityTreeRequirements: ModelWithMetadata<SchemaToEntityMap['ability-tree-requirements']>;
    static Actions: ModelWithMetadata<SchemaToEntityMap['actions']>;
    static Chassis: ModelWithMetadata<SchemaToEntityMap['chassis']>;
    static Classes: ModelWithMetadata<SchemaToEntityMap['classes']>;
    static CrawlerBays: ModelWithMetadata<SchemaToEntityMap['crawler-bays']>;
    static CrawlerTechLevels: ModelWithMetadata<SchemaToEntityMap['crawler-tech-levels']>;
    static Crawlers: ModelWithMetadata<SchemaToEntityMap['crawlers']>;
    static Creatures: ModelWithMetadata<SchemaToEntityMap['creatures']>;
    static Distances: ModelWithMetadata<SchemaToEntityMap['distances']>;
    static Drones: ModelWithMetadata<SchemaToEntityMap['drones']>;
    static Equipment: ModelWithMetadata<SchemaToEntityMap['equipment']>;
    static Factions: ModelWithMetadata<SchemaToEntityMap['factions']>;
    static Guides: ModelWithMetadata<SchemaToEntityMap['guides']>;
    static Keywords: ModelWithMetadata<SchemaToEntityMap['keywords']>;
    static Meld: ModelWithMetadata<SchemaToEntityMap['meld']>;
    static Modules: ModelWithMetadata<SchemaToEntityMap['modules']>;
    static NPCs: ModelWithMetadata<SchemaToEntityMap['npcs']>;
    static RollTables: ModelWithMetadata<SchemaToEntityMap['roll-tables']>;
    static Squads: ModelWithMetadata<SchemaToEntityMap['squads']>;
    static Systems: ModelWithMetadata<SchemaToEntityMap['systems']>;
    static BioTitans: ModelWithMetadata<SchemaToEntityMap['bio-titans']>;
    static Traits: ModelWithMetadata<SchemaToEntityMap['traits']>;
    static Vehicles: ModelWithMetadata<SchemaToEntityMap['vehicles']>;
    static Sources: ModelWithMetadata<SchemaToEntityMap['sources']>;
    static TechLevels: ModelWithMetadata<SchemaToEntityMap['tech-levels']>;
    static CatalogCategories: ModelWithMetadata<SchemaToEntityMap['catalog-categories']>;
    static preload(schemas: string[] | 'all', options?: LoadOptions): Promise<void>;
    static isLoaded(schemaId: string): boolean;
    static findIn<T extends keyof SchemaToEntityMap>(schemaName: T, predicate: (entity: SchemaToEntityMap[T]) => boolean): (SchemaToEntityMap[T] & {
        schemaName: T;
    }) | undefined;
    static findAllIn<T extends keyof SchemaToEntityMap>(schemaName: T, predicate: (entity: SchemaToEntityMap[T]) => boolean): (SchemaToEntityMap[T] & {
        schemaName: T;
    })[];
    static get<T extends keyof SchemaToEntityMap>(schemaName: T, id: string): (SchemaToEntityMap[T] & {
        schemaName: T;
    }) | undefined;
    static getByNameIn<T extends keyof SchemaToEntityMap>(schemaName: T, name: string): (SchemaToEntityMap[T] & {
        schemaName: T;
    }) | undefined;
    static exists<T extends keyof SchemaToEntityMap>(schemaName: T, id: string): boolean;
    static getMany(requests: Array<{
        schemaName: keyof SchemaToEntityMap;
        id: string;
    }>): ((SchemaToEntityMap[keyof SchemaToEntityMap] & {
        schemaName: keyof SchemaToEntityMap;
    }) | undefined)[];
    static parseRef(ref: string): {
        schemaName: SURefEnumSchemaName;
        id: string;
    } | null;
    static getByRef(ref: string): (SchemaToEntityMap[keyof SchemaToEntityMap] & {
        schemaName: keyof SchemaToEntityMap;
    }) | undefined;
    static search(options: SearchOptions): SearchResult[];
    static searchIn<T extends SURefEntity>(schemaName: SURefEnumSchemaName, query: string, options?: {
        limit?: number;
    }): (T & {
        schemaName: SURefEnumSchemaName;
    })[];
    static getSuggestions(query: string, options?: {
        schemas?: SURefEnumSchemaName[];
        limit?: number;
    }): string[];
    static resolveActions(entity: SURefMetaEntity): SURefMetaAction[] | undefined;
    static getAllBySchemaNames<K extends keyof SchemaToEntityMap>(schemaNames: K[]): Array<{
        schemaName: K;
        entity: SchemaToEntityMap[K];
    }>;
}
export declare function resetAllForTesting(): void;
//# sourceMappingURL=index.d.ts.map
// === lib/inventorySlots.d.ts ===
import type { SURefMetaEntity } from './schemas/index.js';
export declare function getInventorySlots(entity: SURefMetaEntity): number;
//# sourceMappingURL=inventorySlots.d.ts.map
// === lib/nameToSlug.d.ts ===
export declare function nameToSlug(name: string): string;
//# sourceMappingURL=nameToSlug.d.ts.map
// === lib/naming.d.ts ===
export declare function toPascalCase(id: string): string;
//# sourceMappingURL=naming.d.ts.map
// === lib/patterns.d.ts ===
import type { SURefMetaEntity, SURefObjectPattern } from './schemas/index.js';
export declare function getPatterns(entity: SURefMetaEntity): SURefObjectPattern[] | undefined;
export declare function isHiddenPattern(hidden: boolean | undefined): boolean;
export declare function visiblePatterns<T extends {
    hidden?: boolean;
}>(patterns: readonly T[]): T[];
export declare function normalizePatternName(patternName: string): string;
//# sourceMappingURL=patterns.d.ts.map
// === lib/printedNameDeviations.d.ts ===
export type Deviation = {
    schema: 'Modules' | 'Systems' | 'Equipment' | 'CrawlerBays';
    name: string;
    printedAs: string;
    page: number;
    why: string;
};
export declare const DEVIATIONS: Deviation[];
//# sourceMappingURL=printedNameDeviations.d.ts.map
// === lib/resolveChoiceView.d.ts ===
import type { SURefObjectChoice, SURefObjectContentBlock, SURefObjectDataValue, SURefObjectTrait } from './schemas/index.js';
export type ChoiceSelections = Record<string, string[]>;
export type ChoicePrompt = {
    choiceId: string;
    label: string;
    text: string;
};
export type ResolvedChoiceView = {
    datavalues: SURefObjectDataValue[];
    traits: SURefObjectTrait[];
    prompts: ChoicePrompt[];
};
type ResolvableEntity = {
    content?: SURefObjectContentBlock[];
    traits?: SURefObjectTrait[];
    choices?: SURefObjectChoice[];
};
export declare function resolveChoiceView(entity: ResolvableEntity, selections: ChoiceSelections): ResolvedChoiceView;
export {};
//# sourceMappingURL=resolveChoiceView.d.ts.map
// === lib/rollOnTable.d.ts ===
import type { SURefObjectTable } from './schemas/index.js';
export type D20Roller = () => number;
export type RollOnTableOutcome = {
    success: true;
    kind: 'flat';
    roll: number;
    key: string;
    label?: string;
    value: string;
} | {
    success: true;
    kind: 'columns';
    columnRoll: number;
    entryRoll: number;
    columnKey: string;
    entryKey: string | number;
    label?: string;
    value: string;
} | {
    success: false;
    error: string;
};
export declare function rollOnTable(table: SURefObjectTable | undefined, rollD20: D20Roller): RollOnTableOutcome;
//# sourceMappingURL=rollOnTable.d.ts.map
// === lib/rules/advancement.d.ts ===
export type AdvancementClassInput = {
    name: string;
    coreTrees?: readonly string[] | undefined;
    advancedTree?: string | undefined;
    legendaryTree?: string | undefined;
    hybrid?: boolean | undefined;
    advanceable?: boolean | undefined;
};
export type AdvancementRequirementInput = {
    name: string;
    requirement: readonly string[];
};
export type AdvancementDataset = {
    classes: readonly AdvancementClassInput[];
    requirements: readonly AdvancementRequirementInput[];
};
export type AdvancementOption = {
    name: string;
    kind: 'advanced' | 'hybrid';
    gateTree: string;
    grantedTree?: string;
    sealedTrees: readonly string[];
};
export type AdvancementTrees = {
    open: readonly string[];
    sealed: readonly string[];
    gate?: string;
    originUnresolved: boolean;
};
export type OriginInferenceState = 'determined' | 'ambiguous' | 'contradictory';
export type OriginInference = {
    state: OriginInferenceState;
    origin?: string;
    candidates: readonly string[];
    unexplainedTrees: readonly string[];
};
export declare function hybridGrantedTrees(data: AdvancementDataset, hybridName: string): string[];
export declare function originsForHybrid(data: AdvancementDataset, hybridName: string): string[];
export declare function gateTreeFor(data: AdvancementDataset, originName: string, hybridName: string): string | undefined;
export declare function advancementOptionsFor(data: AdvancementDataset, baseClassName: string): AdvancementOption[];
export declare function inferOriginClass(data: AdvancementDataset, hybridName: string, heldTrees: readonly string[]): OriginInference;
export declare function resolveAdvancementTrees(data: AdvancementDataset, originName: string | undefined, destName: string | undefined): AdvancementTrees;
//# sourceMappingURL=advancement.d.ts.map
// === lib/rules/advancementDataset.d.ts ===
import type { SURefClass } from '../schemas/index.js';
import type { AdvancementClassInput, AdvancementDataset } from './advancement.js';
export declare function toAdvancementClass(cls: SURefClass): AdvancementClassInput;
export declare function liveAdvancementDataset(): AdvancementDataset;
export declare function offeredAbilityTrees(cls: AdvancementClassInput, options: {
    allLevels: boolean;
    selectedTrees?: readonly string[];
}): string[];
//# sourceMappingURL=advancementDataset.d.ts.map
// === lib/rules/capacity.d.ts ===
import type { MechCapacityResult, MechInput } from './types.js';
export declare function computeMechCapacity(mech: MechInput): MechCapacityResult;
//# sourceMappingURL=capacity.d.ts.map
// === lib/rules/choiceCatalog.d.ts ===
import type { SURefMetaEntity, SURefObjectChoice } from '../schemas/index.js';
export declare function resolveCatalogChoiceEntities(choice: SURefObjectChoice, opts?: {
    techLevel?: number;
}): SURefMetaEntity[];
export declare function isSchemaOnlyCatalogChoice(choice: SURefObjectChoice): boolean;
//# sourceMappingURL=choiceCatalog.d.ts.map
// === lib/rules/contributions.d.ts ===
export type ContributionStat = 'structurePoints' | 'energyPoints' | 'heatCapacity' | 'cargoCapacity' | 'systemSlots' | 'moduleSlots' | 'maxHp' | 'maxAp' | 'inventorySlots';
export type ContributionTarget = 'self' | 'pilot' | 'pilotedMech' | 'crawler';
export type ContributionAmount = number | {
    flat?: number;
    perTechLevel: number;
} | {
    fromStat: ContributionStat;
};
export type DeclaredContribution = {
    stat: ContributionStat;
    amount: ContributionAmount;
    target?: ContributionTarget;
    stacks?: boolean;
    voidWhen?: 'damaged' | 'destroyed';
    duration?: 'permanent' | 'activated';
    note?: string;
};
export type ResolvedContribution = {
    source: string;
    ref: string;
    stat: ContributionStat;
    amount: number;
    copies: number;
};
export declare function resolveAmount(amount: ContributionAmount, techLevel?: number, stats?: Partial<Record<ContributionStat, number>>): number;
export type ActiveEffects = Readonly<Record<string, boolean>>;
export declare function abilityContributions(abilityRefs: readonly string[] | undefined, target: ContributionTarget, stat: ContributionStat, techLevel?: number, active?: ActiveEffects, stats?: Partial<Record<ContributionStat, number>>): ResolvedContribution[];
export declare function sumContributions(contributions: readonly ResolvedContribution[]): number;
export declare function installedContributions(installedRefs: readonly string[] | undefined, stat: ContributionStat, options?: {
    techLevel?: number;
    active?: ActiveEffects;
    stats?: Partial<Record<ContributionStat, number>>;
}): ResolvedContribution[];
//# sourceMappingURL=contributions.d.ts.map
// === lib/rules/coreMechanic.d.ts ===
import type { HeatCheckEffect, Roll } from './types.js';
export type CoreRollBand = 'nailed' | 'success' | 'tough' | 'failure' | 'cascade';
export type CoreRollBandInfo = {
    band: CoreRollBand;
    label: string;
    range: string;
    summary: string;
};
export declare const CORE_ROLL_BANDS: Record<CoreRollBand, CoreRollBandInfo>;
export declare function coreRollBand(roll: number): CoreRollBand;
export type CoreRollResult = {
    roll: number;
    band: CoreRollBand;
};
export declare function performCoreRoll(roll: Roll): CoreRollResult;
export declare function describeOverloadOutcome(result: HeatCheckEffect['result']): string;
export declare function describePushOutcome(nextHeat: number, effect: HeatCheckEffect): string;
//# sourceMappingURL=coreMechanic.d.ts.map
// === lib/rules/crawlerCapacity.d.ts ===
export type CrawlerCapacityInput = {
    techLevel: number;
    bays: string[];
    weaponSystems: string[];
    isBattleCrawler?: boolean;
};
export type CrawlerCapacityViolation = {
    kind: 'bays-over-capacity';
    message: string;
    details: {
        used: number;
        max: number;
    };
} | {
    kind: 'weapon-systems-over-capacity';
    message: string;
    details: {
        used: number;
        max: number;
    };
} | {
    kind: 'tech-level-unknown';
    message: string;
    details: {
        techLevel: number;
    };
};
export type CrawlerCapacityResult = {
    baysUsed: number;
    baysMax: number;
    weaponSystemsUsed: number;
    weaponSystemsMax: number;
    violations: CrawlerCapacityViolation[];
};
export declare function computeCrawlerCapacity(crawler: CrawlerCapacityInput): CrawlerCapacityResult;
//# sourceMappingURL=crawlerCapacity.d.ts.map
// === lib/rules/crawlerSystems.d.ts ===
import type { SURefSystem } from '../schemas/index.js';
export declare function isWeaponSystem(system: SURefSystem): boolean;
//# sourceMappingURL=crawlerSystems.d.ts.map
// === lib/rules/creation.d.ts ===
export type CreationAbilityInput = {
    level: number | string;
    tree: string;
};
export type CreationEquipmentInput = {
    techLevel?: number | string;
};
export type CreationCoreTrees = readonly string[] | undefined;
export declare function isLegalCreationClass(coreTrees: CreationCoreTrees): boolean;
export declare function isLegalCreationAbility(ability: CreationAbilityInput, coreTrees: CreationCoreTrees): boolean;
export declare function legalCreationAbilities<T extends CreationAbilityInput>(abilities: readonly T[], coreTrees: CreationCoreTrees): T[];
export declare function isLegalCreationEquipment(item: CreationEquipmentInput): boolean;
export declare const PILOT_CREATION_ABILITY_PICKS = 1;
export declare const PILOT_CREATION_EQUIPMENT_PICKS = 2;
export declare function pilotEquipmentPicksRemaining(selectedCount: number): number;
export declare function isPilotAbilityPickComplete(selectedCount: number): boolean;
export declare function isPilotEquipmentPickComplete(selectedCount: number): boolean;
export declare function isLegalCreationChassis(techLevel: number | string): boolean;
export declare function isLegalCreationSystem(techLevel: number | string): boolean;
export declare function isLegalCreationModule(techLevel: number | string): boolean;
export type CreationPatternInput = {
    legalStarting?: boolean;
};
export declare function isLegalStartingPattern(legalStarting: boolean | undefined): boolean;
export declare function legalStartingPatterns<T extends CreationPatternInput>(patterns: readonly T[]): T[];
export declare const MECH_CREATION_SCRAP_CAP = 20;
export type MechCreationLoadoutEntry = {
    sv: number;
    count: number;
};
export type MechCreationBudgetInput = {
    chassisSV: number;
    loadout: readonly MechCreationLoadoutEntry[];
};
export type MechCreationBudget = {
    cap: number;
    spent: number;
    remaining: number;
    perItemAffordable: (sv: number) => boolean;
};
export declare function mechCreationBudget(input: MechCreationBudgetInput): MechCreationBudget;
export declare const CRAWLER_CREATION_TECH_LEVEL = 1;
export declare function isLegalCreationCrawlerWeapon(techLevel: number | string): boolean;
export type CrawlerMutationInput = {
    type: string;
    value: number;
};
export declare function crawlerWeaponSlots(mutations: readonly CrawlerMutationInput[] | undefined): number;
export declare function crawlerMaxSpBonus(mutations: readonly CrawlerMutationInput[] | undefined): number;
export declare const CRAWLER_CREATION_MIN_WEAPONS = 1;
export declare function isCrawlerWeaponPickComplete(selectedCount: number): boolean;
//# sourceMappingURL=creation.d.ts.map
// === lib/rules/derivedStats.d.ts ===
import type { ActiveEffects, ResolvedContribution } from './contributions.js';
export declare const PILOT_BASE_HP = 10;
export declare const PILOT_BASE_AP = 5;
export declare const PILOT_BASE_INVENTORY_SLOTS = 6;
export declare function resolvePool(current: number | undefined, max: number): number;
export declare function resolvePoolStart(current: number | undefined, max: number): number;
export declare function resolveGauge(current: number | undefined, max?: number): number;
type Injury = {
    severity: 'minor' | 'major';
    note: string;
};
type PilotDerivationInput = {
    abilities?: string[];
    crawlerTechLevel?: number;
    injuries?: Injury[];
    maxHpModifier?: number;
    maxApModifier?: number;
    maxInventorySlotsModifier?: number;
    maxHpOverride?: number;
    maxApOverride?: number;
    maxInventorySlotsOverride?: number;
};
export declare function injuryMaxHpPenalty(injuries: Injury[] | undefined): number;
export declare function pilotMaxHPParts(pilot: PilotDerivationInput): StatBreakdown;
export declare function pilotMaxHP(pilot: PilotDerivationInput): number;
export declare function pilotMaxAPParts(pilot: PilotDerivationInput): StatBreakdown;
export declare function pilotMaxAP(pilot: PilotDerivationInput): number;
export declare function pilotMaxInventorySlotsParts(pilot: PilotDerivationInput): StatBreakdown;
export declare function pilotMaxInventorySlots(pilot: PilotDerivationInput): number;
export declare function isPilotDead(pilot: PilotDerivationInput): boolean;
export declare function clampPilotCurrentStats(pilot: PilotDerivationInput & {
    currentHP?: number;
    currentAP?: number;
}): Partial<{
    currentHP: number;
    currentAP: number;
}>;
export type ChassisStats = {
    structurePoints?: number;
    energyPoints?: number;
    heatCapacity?: number;
    cargoCapacity?: number;
    systemSlots?: number;
    moduleSlots?: number;
};
type MechDerivationInput = {
    chassisRef: string;
    maxSpModifier?: number;
    maxEpModifier?: number;
    maxHeatModifier?: number;
    maxCargoModifier?: number;
    maxSpOverride?: number;
    maxEpOverride?: number;
    maxHeatOverride?: number;
    maxCargoOverride?: number;
    systems?: string[];
    modules?: string[];
};
export type PilotingContext = {
    abilities?: string[];
    techLevel?: number;
    active?: ActiveEffects;
};
export type StatBreakdown = {
    base: number;
    installed: number;
    sources: ResolvedContribution[];
    adjustment: number;
    derived: number;
    override?: number;
    total: number;
    overridden: boolean;
};
export declare function mechMaxSPParts(mech: MechDerivationInput, chassis?: ChassisStats | null, pilot?: PilotingContext): StatBreakdown;
export declare function mechMaxEPParts(mech: MechDerivationInput, chassis?: ChassisStats | null, pilot?: PilotingContext): StatBreakdown;
export declare function mechMaxHeatParts(mech: MechDerivationInput, chassis?: ChassisStats | null, pilot?: PilotingContext): StatBreakdown;
export declare function mechMaxCargoParts(mech: MechDerivationInput, chassis?: ChassisStats | null, pilot?: PilotingContext): StatBreakdown;
export declare function mechMaxSP(mech: MechDerivationInput, chassis?: ChassisStats | null, pilot?: PilotingContext): number;
export declare function mechMaxEP(mech: MechDerivationInput, chassis?: ChassisStats | null, pilot?: PilotingContext): number;
export declare function mechMaxHeat(mech: MechDerivationInput, chassis?: ChassisStats | null, pilot?: PilotingContext): number;
export declare function mechMaxCargo(mech: MechDerivationInput, chassis?: ChassisStats | null, pilot?: PilotingContext): number;
export declare function clampMechCurrentStats(mech: MechDerivationInput & {
    currentSP?: number;
    currentEP?: number;
    currentHeat?: number;
}, chassis?: ChassisStats | null): Partial<{
    currentSP: number;
    currentEP: number;
    currentHeat: number;
}>;
export declare function unifiedMechConditions(mech: {
    conditions: string[];
    shutdown?: boolean;
    vulnerable?: boolean;
    destroyed?: boolean;
}): string[];
type CrawlerDerivationInput = {
    techLevel: string;
    maxSpOverride?: number;
    type?: string;
    maxSpModifier?: number;
};
export type CrawlerMaxSPParts = StatBreakdown & {
    typeBonus: number;
};
export declare function crawlerMaxSPParts(crawler: CrawlerDerivationInput): CrawlerMaxSPParts;
export declare function crawlerMaxSP(crawler: CrawlerDerivationInput): number;
export declare function clampCrawlerCurrentStats(crawler: CrawlerDerivationInput & {
    currentSP?: number;
}): Partial<{
    currentSP: number;
}>;
export {};
//# sourceMappingURL=derivedStats.d.ts.map
// === lib/rules/heatCheck.d.ts ===
import type { HeatCheckEffect, PushResult, ReactorOverloadOutcome, Roll } from './types.js';
export declare function clampHeat(heat: number, cap: number): number;
export declare function canActivateAction(currentHeat: number, heatCost: number, heatCap: number): boolean;
export declare function reactorOverloadOutcome(roll: number): ReactorOverloadOutcome;
type HeatCheckInput = {
    heat: number;
    currentSP: number;
    roll: Roll;
    now?: () => Date;
};
export declare function performHeatCheck({ heat, currentSP, roll, now }: HeatCheckInput): HeatCheckEffect;
type PushInput = {
    heat: number;
    heatCap: number;
    currentSP: number;
    roll: Roll;
    now?: () => Date;
};
export declare function performPush({ heat, heatCap, currentSP, roll, now }: PushInput): PushResult;
export {};
//# sourceMappingURL=heatCheck.d.ts.map
// === lib/rules/index.d.ts ===
export type { AdvancementOption } from './advancement.js';
export { advancementOptionsFor, originsForHybrid, resolveAdvancementTrees, } from './advancement.js';
export { liveAdvancementDataset, offeredAbilityTrees, } from './advancementDataset.js';
export { computeMechCapacity } from './capacity.js';
export { isSchemaOnlyCatalogChoice, resolveCatalogChoiceEntities, } from './choiceCatalog.js';
export { abilityContributions, sumContributions, } from './contributions.js';
export type { CoreRollBand, CoreRollBandInfo, CoreRollResult } from './coreMechanic.js';
export { CORE_ROLL_BANDS, coreRollBand, describeOverloadOutcome, describePushOutcome, performCoreRoll, } from './coreMechanic.js';
export type { CrawlerCapacityInput, CrawlerCapacityResult, CrawlerCapacityViolation, } from './crawlerCapacity.js';
export { computeCrawlerCapacity } from './crawlerCapacity.js';
export { isWeaponSystem } from './crawlerSystems.js';
export type { CrawlerMutationInput, MechCreationBudget, } from './creation.js';
export { crawlerMaxSpBonus, crawlerWeaponSlots, isCrawlerWeaponPickComplete, isLegalCreationAbility, isLegalCreationChassis, isLegalCreationClass, isLegalCreationCrawlerWeapon, isLegalCreationEquipment, isLegalCreationModule, isLegalCreationSystem, isLegalStartingPattern, isPilotAbilityPickComplete, isPilotEquipmentPickComplete, legalCreationAbilities, legalStartingPatterns, MECH_CREATION_SCRAP_CAP, mechCreationBudget, PILOT_CREATION_ABILITY_PICKS, PILOT_CREATION_EQUIPMENT_PICKS, pilotEquipmentPicksRemaining, } from './creation.js';
export type { ChassisStats, CrawlerMaxSPParts, StatBreakdown } from './derivedStats.js';
export { clampCrawlerCurrentStats, clampMechCurrentStats, clampPilotCurrentStats, crawlerMaxSP, crawlerMaxSPParts, injuryMaxHpPenalty, isPilotDead, mechMaxCargo, mechMaxCargoParts, mechMaxEP, mechMaxEPParts, mechMaxHeat, mechMaxHeatParts, mechMaxSP, mechMaxSPParts, PILOT_BASE_AP, PILOT_BASE_HP, PILOT_BASE_INVENTORY_SLOTS, pilotMaxAP, pilotMaxAPParts, pilotMaxHP, pilotMaxHPParts, pilotMaxInventorySlots, pilotMaxInventorySlotsParts, resolveGauge, resolvePool, resolvePoolStart, unifiedMechConditions, } from './derivedStats.js';
export { canActivateAction, clampHeat, performHeatCheck, performPush, reactorOverloadOutcome, } from './heatCheck.js';
export { enrichPilotSnapshot } from './pilotSnapshot.js';
export { matchesRef, resolveChassisRef, resolveCrawlerBayRef, resolveCrawlerRef, resolveInstalledRef, resolveModuleRef, resolveRef, resolveSystemRef, } from './resolveRefs.js';
export { statesMechanicalChange } from './rulesBearing.js';
export { scrapCostFor, tierUpgradeCost } from './scrap.js';
export { evaluateMechWarnings, evaluatePilotWarnings, evaluateSoftWarnings, } from './softWarnings.js';
export type { CriticalDamageEffect, CriticalInjuryEffect, DamageKind, MechDamageEffect, MechDamageInput, PilotDamageEffect, PilotDamageInput, } from './takeDamage.js';
export { applyMechDamage, applyPilotDamage, criticalDamageOutcome, criticalInjuryOutcome, mechEffectiveDamage, performCriticalDamage, performCriticalInjury, pilotEffectiveDamage, } from './takeDamage.js';
export type { AbilityInput, AbilityTier, CapacityViolation, CargoCapacityResult, CargoItem, CargoItemCustom, CargoItemRef, CargoParent, CargoViolation, EditSnapshot, HeatCheckEffect, MechCapacityResult, MechInput, MechModuleSlot, MechSnapshot, MechSystemSlot, PilotSnapshot, PushResult, Roll, ScrapableItem, SoftWarning, SoftWarningContext, SoftWarningSeverity, SystemSnapshot, TechLevel, } from './types.js';
//# sourceMappingURL=index.d.ts.map
// === lib/rules/mediatorTables.d.ts ===
import type { MediatorRollResult, MediatorTableId, Roll } from './types.js';
export declare const MEDIATOR_TABLE_NAMES: Record<MediatorTableId, string>;
export declare const MEDIATOR_TABLE_LABEL: Record<MediatorTableId, string>;
export type FindRollTable = (name: string) => {
    table?: unknown;
} | undefined;
type MediatorRollInput = {
    table: MediatorTableId;
    roll: Roll;
    findTable: FindRollTable;
    now?: () => Date;
};
export declare function performMediatorRoll({ table, roll, findTable, now, }: MediatorRollInput): MediatorRollResult | null;
export declare function describeMediatorRoll(result: MediatorRollResult): string;
export {};
//# sourceMappingURL=mediatorTables.d.ts.map
// === lib/rules/pilotSnapshot.d.ts ===
import type { PilotSnapshot } from './types.js';
export declare function enrichPilotSnapshot(pilot: {
    abilities: string[];
    classRef?: string;
}): PilotSnapshot;
//# sourceMappingURL=pilotSnapshot.d.ts.map
// === lib/rules/resolveRefs.d.ts ===
import type { SURefChassis, SURefCrawler, SURefCrawlerBay, SURefModule, SURefSystem } from '../schemas/index.js';
type Resolved<T> = (T & {
    schemaName: string;
}) | null;
type RefEntity = {
    id: string;
    name?: string;
};
export declare function matchesRef(entity: RefEntity, ref: string): boolean;
type ModelLike<T extends RefEntity> = {
    getById: (id: string) => T | undefined;
    getByName: (name: string) => T | undefined;
    getBySlug: (slug: string) => T | undefined;
};
export declare function resolveRef<T extends RefEntity>(model: ModelLike<T>, ref: string): T | null;
export declare function resolveChassisRef(ref: string): Resolved<SURefChassis>;
export declare function resolveSystemRef(ref: string): Resolved<SURefSystem>;
export declare function resolveModuleRef(ref: string): Resolved<SURefModule>;
export declare function resolveInstalledRef(ref: string): Resolved<SURefSystem | SURefModule>;
export declare function resolveCrawlerRef(ref: string): Resolved<SURefCrawler>;
export declare function resolveCrawlerBayRef(ref: string): Resolved<SURefCrawlerBay>;
export {};
//# sourceMappingURL=resolveRefs.d.ts.map
// === lib/rules/rulesBearing.d.ts ===
export type RulesClaim = 'cap' | 'effect';
export declare function statesMechanicalChange(text: string | undefined): RulesClaim | null;
//# sourceMappingURL=rulesBearing.d.ts.map
// === lib/rules/scrap.d.ts ===
import type { ScrapableItem, TechLevel } from './types.js';
export declare function salvageValueFor(item: ScrapableItem): number;
export declare function scrapCostFor(item: ScrapableItem): number;
export declare function tierUpgradeCost(fromTL: TechLevel, toTL: TechLevel): number | null;
//# sourceMappingURL=scrap.d.ts.map
// === lib/rules/softWarnings.d.ts ===
import type { EditSnapshot, MechSnapshot, PilotSnapshot, SoftWarning, SoftWarningContext } from './types.js';
export declare const PILOT_ABILITY_CAP = 10;
export declare const SALVAGER_ABILITY_CAP = 12;
export declare function evaluatePilotWarnings(snapshot: EditSnapshot<PilotSnapshot>, context: SoftWarningContext): SoftWarning[];
export declare function evaluateMechWarnings(snapshot: EditSnapshot<MechSnapshot>, context: SoftWarningContext): SoftWarning[];
export declare function evaluateSoftWarnings(before: PilotSnapshot | MechSnapshot, after: PilotSnapshot | MechSnapshot, context: SoftWarningContext): SoftWarning[];
//# sourceMappingURL=softWarnings.d.ts.map
// === lib/rules/takeDamage.d.ts ===
import type { CriticalDamageOutcome, CriticalDamageResult, CriticalInjuryOutcome, CriticalInjuryResult, Roll } from './types.js';
export type DamageKind = 'sp' | 'hp';
export declare function applySpDamage(currentSp: number, damage: number): {
    newSp: number;
    hpDamage: number;
};
export declare function mechEffectiveDamage(amount: number, kind: DamageKind, vulnerable: boolean): number;
export type MechDamageInput = {
    currentSP: number;
    amount: number;
    kind: DamageKind;
    vulnerable: boolean;
};
export type MechDamageEffect = {
    effectiveDamage: number;
    nextSP: number;
    criticalDue: boolean;
};
export declare function applyMechDamage({ currentSP, amount, kind, vulnerable, }: MechDamageInput): MechDamageEffect;
export declare function criticalDamageOutcome(roll: number): CriticalDamageOutcome;
export type CriticalDamageEffect = {
    result: CriticalDamageResult;
    nextSP: number | null;
    destroyed: boolean;
    chassisDamaged: boolean;
    requiresPlayerChoice: 'system' | 'module' | null;
};
type CriticalRollInput = {
    roll: Roll;
    now?: () => Date;
};
export declare function performCriticalDamage({ roll, now }: CriticalRollInput): CriticalDamageEffect;
export declare function pilotEffectiveDamage(amount: number, kind: DamageKind, vulnerable: boolean): number;
export type PilotDamageInput = {
    currentHP: number;
    amount: number;
    kind: DamageKind;
    vulnerable: boolean;
};
export type PilotDamageEffect = {
    effectiveDamage: number;
    nextHP: number;
    criticalDue: boolean;
};
export declare function applyPilotDamage({ currentHP, amount, kind, vulnerable, }: PilotDamageInput): PilotDamageEffect;
export declare function criticalInjuryOutcome(roll: number): CriticalInjuryOutcome;
export type CriticalInjuryEffect = {
    result: CriticalInjuryResult;
    nextHP: number | null;
    unconscious: boolean;
    injury: 'minor' | 'major' | null;
    fatal: boolean;
};
export declare function performCriticalInjury({ roll, now }: CriticalRollInput): CriticalInjuryEffect;
export {};
//# sourceMappingURL=takeDamage.d.ts.map
// === lib/rules/types.d.ts ===
export type TechLevel = 1 | 2 | 3 | 4 | 5 | 6 | 'B' | 'N';
export type MechSystemSlot = {
    ref: string;
    slotCost?: number;
};
export type MechModuleSlot = {
    ref: string;
    slotCost?: number;
};
export type MechInput = {
    chassisRef: string;
    systems: MechSystemSlot[];
    modules: MechModuleSlot[];
};
export type CapacityViolation = {
    kind: 'system-over-slots';
    message: string;
    details: {
        used: number;
        max: number;
    };
} | {
    kind: 'module-over-slots';
    message: string;
    details: {
        used: number;
        max: number;
    };
} | {
    kind: 'system-requires-chassis';
    message: string;
    details: {
        systemRef: string;
        requiredChassis: string;
    };
} | {
    kind: 'chassis-not-found';
    message: string;
    details: {
        chassisRef: string;
    };
};
export type MechCapacityResult = {
    systemSlotsUsed: number;
    systemSlotsMax: number;
    moduleSlotsUsed: number;
    moduleSlotsMax: number;
    violations: CapacityViolation[];
};
export type CargoItemRef = {
    kind: 'ref';
    ref: string;
    slotCount?: number;
};
export type CargoItemCustom = {
    kind: 'custom';
    name: string;
    slotCount: number;
};
export type CargoItem = CargoItemRef | CargoItemCustom;
export type CargoParent = {
    cargoCapacity: number;
};
export type CargoViolation = {
    kind: 'over-capacity';
    message: string;
    details: {
        used: number;
        max: number;
    };
} | {
    kind: 'missing-ref';
    message: string;
    details: {
        ref: string;
    };
};
export type CargoCapacityResult = {
    used: number;
    max: number;
    violations: CargoViolation[];
};
export type ScrapableItem = {
    salvageValue: number;
    techLevel: TechLevel;
};
export type SoftWarningSeverity = 'info' | 'warn';
export type SoftWarning = {
    code: string;
    message: string;
    severity: SoftWarningSeverity;
};
export type AbilityTier = 'core' | 'advanced' | 'legendary';
export type AbilityInput = {
    ref: string;
    name?: string;
    tree?: string;
    level?: number | 'L' | 'G';
    tier?: AbilityTier;
};
export type PilotSnapshot = {
    abilities: AbilityInput[];
    isSalvager?: boolean;
    maxAbilities?: number;
    classTier?: 'base' | 'advanced-hybrid';
    className?: string;
};
export type SystemSnapshot = {
    ref: string;
    requires?: string[];
};
export type MechSnapshot = {
    techLevel?: TechLevel;
    systems: SystemSnapshot[];
};
export type SoftWarningContext = {
    entityType: 'pilot' | 'mech' | 'crawler';
    techLevelDowngraded?: boolean;
    scrapRefundSkipped?: boolean;
};
export type EditSnapshot<T> = {
    before: T;
    after: T;
};
export type Roll = (sides: number) => number;
export type ReactorOverloadOutcome = 'meltdown' | 'system-destroyed' | 'module-destroyed' | 'overheat' | 'safe';
export type HeatCheckResult = {
    heatCheckRoll: number;
    heatAtCheck: number;
    overloaded: boolean;
    overloadRoll?: number;
    outcome?: ReactorOverloadOutcome;
    rolledAt: string;
};
export type HeatCheckEffect = {
    result: HeatCheckResult;
    nextSP: number;
    shutdown: boolean;
    vulnerable: boolean;
    destroyed: boolean;
    requiresPlayerChoice: boolean;
};
export type PushResult = {
    nextHeat: number;
    effect: HeatCheckEffect;
};
export type CriticalDamageOutcome = 'catastrophic' | 'system-destruction' | 'module-destruction' | 'core-damage' | 'miraculous-survival';
export type CriticalDamageResult = {
    roll: number;
    outcome: CriticalDamageOutcome;
    rolledAt: string;
};
export type CriticalInjuryOutcome = 'fatal' | 'major-injury' | 'minor-injury' | 'unconscious' | 'miraculous-survival';
export type CriticalInjuryResult = {
    roll: number;
    outcome: CriticalInjuryOutcome;
    rolledAt: string;
};
export type MediatorTableId = 'reaction' | 'morale' | 'retreat';
export type MediatorRollResult = {
    table: MediatorTableId;
    roll: number;
    label?: string;
    value: string;
    rolledAt: string;
};
//# sourceMappingURL=types.d.ts.map
// === lib/schemaDefinitions.d.ts ===
export declare function getJsonSchemaDefinition(schemaId: string): Record<string, unknown> | undefined;
//# sourceMappingURL=schemaDefinitions.d.ts.map
// === lib/schemas/index.d.ts ===
import type { z } from '../zod.js';
export type * from '../generated/entityTypes.generated.js';
export * from './common.js';
export * from './entities.js';
export * from './enums.js';
export * from './objects.js';
import type { SchemaNameSchema } from './enums.js';
import type { AdvancedClassSchema, ChoiceSchema, ContentBlockSchema, ContentSchema, DamageSchema, DataValueSchema, GrantSchema, GuideStepSchema, PatternSchema, PatternSystemModuleSchema, StatsSchema, SystemModuleSchema, TableContentSchema, TableSchema, TraitSchema } from './objects.js';
export type SURefEnumSchemaName = z.infer<typeof SchemaNameSchema>;
export type SURefObjectTrait = z.infer<typeof TraitSchema>;
export type SURefObjectDataValue = z.infer<typeof DataValueSchema>;
export type SURefObjectContentBlock = z.infer<typeof ContentBlockSchema>;
export type SURefObjectContent = z.infer<typeof ContentSchema>;
export type SURefObjectTableContent = z.infer<typeof TableContentSchema>;
export type SURefObjectTable = z.infer<typeof TableSchema>;
export type SURefObjectPatternSystemModule = z.infer<typeof PatternSystemModuleSchema>;
export type SURefObjectSystemModule = z.infer<typeof SystemModuleSchema>;
export type SURefObjectChoice = z.infer<typeof ChoiceSchema>;
export type SURefObjectPattern = z.infer<typeof PatternSchema>;
export type SURefObjectDamage = z.infer<typeof DamageSchema>;
export type SURefObjectBonusPerTechLevel = z.infer<typeof StatsSchema>;
export type SURefObjectAdvancedClass = z.infer<typeof AdvancedClassSchema>;
export type SURefObjectGrant = z.infer<typeof GrantSchema>;
export type SURefObjectGuideStep = z.infer<typeof GuideStepSchema>;
//# sourceMappingURL=index.d.ts.map
// === lib/search.d.ts ===
import type { SURefEntity, SURefEnumSchemaName } from './schemas/index.js';
export declare function isSchemaName(id: string): id is SURefEnumSchemaName;
export type SearchOptions = {
    query: string;
    schemas?: SURefEnumSchemaName[];
    limit?: number;
};
export declare function invalidateSearchIndex(): void;
export type SearchResult = {
    schemaName: SURefEnumSchemaName;
    schemaTitle: string;
    entity: SURefEntity & {
        schemaName: SURefEnumSchemaName;
    };
    entityId: string;
    entityName: string;
    matchedFields: string[];
    matchScore: number;
};
export declare function extractContentText(content: unknown): string;
export declare function search(options: SearchOptions): SearchResult[];
export declare function searchIn<T extends SURefEntity>(schemaName: SURefEnumSchemaName, query: string, options?: {
    limit?: number;
}): (T & {
    schemaName: SURefEnumSchemaName;
})[];
export declare function getSuggestions(query: string, options?: {
    schemas?: SURefEnumSchemaName[];
    limit?: number;
}): string[];
//# sourceMappingURL=search.d.ts.map
// === lib/searchRanking.d.ts ===
export type SearchQuery = {
    loweredQuery: string;
    tokens: string[];
};
export declare function tokenizeSearchQuery(query: string): SearchQuery | null;
export declare function searchNameWords(nameText: string): string[];
export declare function matchSearchTokens(tokens: readonly string[], nameWords: readonly string[], hasLiteral: (token: string) => boolean): {
    matches: boolean;
    usedTypo: boolean;
};
export type SearchMatchFacts = SearchQuery & {
    nameText: string;
    usedTypo: boolean;
    descriptionText?: string;
    matchedFieldCount?: number;
};
export declare function scoreSearchMatch(facts: SearchMatchFacts): number;
//# sourceMappingURL=searchRanking.d.ts.map
// === lib/slug.d.ts ===
import type { SURefEntity, SURefEnumSchemaName } from './schemas/index.js';
export declare function findEntityBySlug(schemaName: SURefEnumSchemaName, slug: string): SURefEntity | null;
export declare function getEntitySlug(entity: SURefEntity): string;
//# sourceMappingURL=slug.d.ts.map
// === lib/testing.d.ts ===
import type { EntitySchemaName, SchemaToEntityMap } from './generated/schemaRegistry.generated.js';
export declare function entityFixture<K extends EntitySchemaName>(schemaName: K, fields?: Partial<SchemaToEntityMap[K]>): SchemaToEntityMap[K];
export declare function malformed<T>(value: unknown): T;
//# sourceMappingURL=testing.d.ts.map
// === lib/traitText.d.ts ===
export type ParsedTraitReference = {
    fullMatch: string;
    traitName: string;
    parameter?: string;
    startIndex: number;
    endIndex: number;
};
export declare function parseTraitReferences(text: string): ParsedTraitReference[];
export declare function replaceTraitReferences(text: string, render: (reference: ParsedTraitReference) => string): string;
//# sourceMappingURL=traitText.d.ts.map
// === lib/utils/resultForTable.d.ts ===
import type { SURefObjectTable, SURefObjectTableContent } from '../schemas/index.js';
type ColumnsTable = Extract<SURefObjectTable, {
    type: 'columns';
}>;
export type ColumnsTableRollResult = {
    success: boolean;
    columnKey: string;
    entryKey: string;
    result: SURefObjectTableContent;
};
export declare function isColumnsTable(table: SURefObjectTable | undefined): table is ColumnsTable;
export declare function resultForColumnsTable(table: SURefObjectTable | undefined, columnRoll: number, entryRoll: number): ColumnsTableRollResult;
export type TableRollResult = {
    success: boolean;
    result: SURefObjectTableContent;
    key: string;
};
export declare function resultForTable(table: SURefObjectTable | undefined, roll: number): TableRollResult;
export {};
//# sourceMappingURL=resultForTable.d.ts.map
// === lib/utils/tableRows.d.ts ===
import type { SURefObjectTable } from '../schemas/index.js';
export type TableRow = {
    order: number;
    key: string;
    label: string | null;
    value: string;
};
export declare function tableRows(table: SURefObjectTable | undefined | null): TableRow[];
//# sourceMappingURL=tableRows.d.ts.map
// === lib/validateData.d.ts ===
export declare function validateRows(schemaId: string, rawData: unknown[]): unknown[];
//# sourceMappingURL=validateData.d.ts.map
// === lib/zod.d.ts ===
import { z } from 'zod';
export { z };
//# sourceMappingURL=zod.d.ts.map