/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as EncounterRouteImport } from './routes/encounter'
import { Route as GamesRouteImport } from './routes/games'
import { Route as CrawlersIdRouteImport } from './routes/crawlers/$id'
import { Route as CrawlersNewRouteImport } from './routes/crawlers/new'
import { Route as DashboardIdRouteImport } from './routes/dashboard/$id'
import { Route as MechsIdRouteImport } from './routes/mechs/$id'
import { Route as MechsNewRouteImport } from './routes/mechs/new'
import { Route as MediatorGameIdRouteImport } from './routes/mediator/$gameId'
import { Route as PilotsIdRouteImport } from './routes/pilots/$id'
import { Route as PilotsNewRouteImport } from './routes/pilots/new'
import { Route as SIdRouteImport } from './routes/s/$id'
import { Route as MechsPatternsIndexRouteImport } from './routes/mechs/patterns/index'
import { Route as SheetKindIdRouteImport } from './routes/sheet/$kind/$id'
import { Route as SheetKindIdShareRouteImport } from './routes/sheet/$kind/$id_.share'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const EncounterRoute = EncounterRouteImport.update({
  id: '/encounter',
  path: '/encounter',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const CrawlersIdRoute = CrawlersIdRouteImport.update({
  id: '/crawlers/$id',
  path: '/crawlers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CrawlersNewRoute = CrawlersNewRouteImport.update({
  id: '/crawlers/new',
  path: '/crawlers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIdRoute = DashboardIdRouteImport.update({
  id: '/dashboard/$id',
  path: '/dashboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MechsIdRoute = MechsIdRouteImport.update({
  id: '/mechs/$id',
  path: '/mechs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MechsNewRoute = MechsNewRouteImport.update({
  id: '/mechs/new',
  path: '/mechs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MediatorGameIdRoute = MediatorGameIdRouteImport.update({
  id: '/mediator/$gameId',
  path: '/mediator/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotsIdRoute = PilotsIdRouteImport.update({
  id: '/pilots/$id',
  path: '/pilots/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotsNewRoute = PilotsNewRouteImport.update({
  id: '/pilots/new',
  path: '/pilots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MechsPatternsIndexRoute = MechsPatternsIndexRouteImport.update({
  id: '/mechs/patterns/',
  path: '/mechs/patterns/',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetKindIdRoute = SheetKindIdRouteImport.update({
  id: '/sheet/$kind/$id',
  path: '/sheet/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetKindIdShareRoute = SheetKindIdShareRouteImport.update({
  id: '/sheet/$kind/$id_/share',
  path: '/sheet/$kind/$id/share',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/changelog': typeof ChangelogRoute
  '/encounter': typeof EncounterRoute
  '/games': typeof GamesRoute
  '/crawlers/$id': typeof CrawlersIdRoute
  '/crawlers/new': typeof CrawlersNewRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/mechs/$id': typeof MechsIdRoute
  '/mechs/new': typeof MechsNewRoute
  '/mediator/$gameId': typeof MediatorGameIdRoute
  '/pilots/$id': typeof PilotsIdRoute
  '/pilots/new': typeof PilotsNewRoute
  '/s/$id': typeof SIdRoute
  '/sheet/$kind/$id': typeof SheetKindIdRoute
  '/mechs/patterns/': typeof MechsPatternsIndexRoute
  '/sheet/$kind/$id/share': typeof SheetKindIdShareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/changelog': typeof ChangelogRoute
  '/encounter': typeof EncounterRoute
  '/games': typeof GamesRoute
  '/crawlers/$id': typeof CrawlersIdRoute
  '/crawlers/new': typeof CrawlersNewRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/mechs/$id': typeof MechsIdRoute
  '/mechs/new': typeof MechsNewRoute
  '/mediator/$gameId': typeof MediatorGameIdRoute
  '/pilots/$id': typeof PilotsIdRoute
  '/pilots/new': typeof PilotsNewRoute
  '/s/$id': typeof SIdRoute
  '/sheet/$kind/$id': typeof SheetKindIdRoute
  '/mechs/patterns': typeof MechsPatternsIndexRoute
  '/sheet/$kind/$id/share': typeof SheetKindIdShareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/changelog': typeof ChangelogRoute
  '/encounter': typeof EncounterRoute
  '/games': typeof GamesRoute
  '/crawlers/$id': typeof CrawlersIdRoute
  '/crawlers/new': typeof CrawlersNewRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/mechs/$id': typeof MechsIdRoute
  '/mechs/new': typeof MechsNewRoute
  '/mediator/$gameId': typeof MediatorGameIdRoute
  '/pilots/$id': typeof PilotsIdRoute
  '/pilots/new': typeof PilotsNewRoute
  '/s/$id': typeof SIdRoute
  '/sheet/$kind/$id': typeof SheetKindIdRoute
  '/mechs/patterns/': typeof MechsPatternsIndexRoute
  '/sheet/$kind/$id_/share': typeof SheetKindIdShareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/changelog'
    | '/encounter'
    | '/games'
    | '/crawlers/$id'
    | '/crawlers/new'
    | '/dashboard/$id'
    | '/mechs/$id'
    | '/mechs/new'
    | '/mediator/$gameId'
    | '/pilots/$id'
    | '/pilots/new'
    | '/s/$id'
    | '/sheet/$kind/$id'
    | '/mechs/patterns/'
    | '/sheet/$kind/$id/share'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/changelog'
    | '/encounter'
    | '/games'
    | '/crawlers/$id'
    | '/crawlers/new'
    | '/dashboard/$id'
    | '/mechs/$id'
    | '/mechs/new'
    | '/mediator/$gameId'
    | '/pilots/$id'
    | '/pilots/new'
    | '/s/$id'
    | '/sheet/$kind/$id'
    | '/mechs/patterns'
    | '/sheet/$kind/$id/share'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/changelog'
    | '/encounter'
    | '/games'
    | '/crawlers/$id'
    | '/crawlers/new'
    | '/dashboard/$id'
    | '/mechs/$id'
    | '/mechs/new'
    | '/mediator/$gameId'
    | '/pilots/$id'
    | '/pilots/new'
    | '/s/$id'
    | '/sheet/$kind/$id'
    | '/mechs/patterns/'
    | '/sheet/$kind/$id_/share'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  ChangelogRoute: typeof ChangelogRoute
  EncounterRoute: typeof EncounterRoute
  GamesRoute: typeof GamesRoute
  CrawlersIdRoute: typeof CrawlersIdRoute
  CrawlersNewRoute: typeof CrawlersNewRoute
  DashboardIdRoute: typeof DashboardIdRoute
  MechsIdRoute: typeof MechsIdRoute
  MechsNewRoute: typeof MechsNewRoute
  MediatorGameIdRoute: typeof MediatorGameIdRoute
  PilotsIdRoute: typeof PilotsIdRoute
  PilotsNewRoute: typeof PilotsNewRoute
  SIdRoute: typeof SIdRoute
  SheetKindIdRoute: typeof SheetKindIdRoute
  MechsPatternsIndexRoute: typeof MechsPatternsIndexRoute
  SheetKindIdShareRoute: typeof SheetKindIdShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encounter': {
      id: '/encounter'
      path: '/encounter'
      fullPath: '/encounter'
      preLoaderRoute: typeof EncounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crawlers/$id': {
      id: '/crawlers/$id'
      path: '/crawlers/$id'
      fullPath: '/crawlers/$id'
      preLoaderRoute: typeof CrawlersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crawlers/new': {
      id: '/crawlers/new'
      path: '/crawlers/new'
      fullPath: '/crawlers/new'
      preLoaderRoute: typeof CrawlersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechs/$id': {
      id: '/mechs/$id'
      path: '/mechs/$id'
      fullPath: '/mechs/$id'
      preLoaderRoute: typeof MechsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechs/new': {
      id: '/mechs/new'
      path: '/mechs/new'
      fullPath: '/mechs/new'
      preLoaderRoute: typeof MechsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediator/$gameId': {
      id: '/mediator/$gameId'
      path: '/mediator/$gameId'
      fullPath: '/mediator/$gameId'
      preLoaderRoute: typeof MediatorGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilots/$id': {
      id: '/pilots/$id'
      path: '/pilots/$id'
      fullPath: '/pilots/$id'
      preLoaderRoute: typeof PilotsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilots/new': {
      id: '/pilots/new'
      path: '/pilots/new'
      fullPath: '/pilots/new'
      preLoaderRoute: typeof PilotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechs/patterns/': {
      id: '/mechs/patterns/'
      path: '/mechs/patterns'
      fullPath: '/mechs/patterns/'
      preLoaderRoute: typeof MechsPatternsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheet/$kind/$id': {
      id: '/sheet/$kind/$id'
      path: '/sheet/$kind/$id'
      fullPath: '/sheet/$kind/$id'
      preLoaderRoute: typeof SheetKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheet/$kind/$id_/share': {
      id: '/sheet/$kind/$id_/share'
      path: '/sheet/$kind/$id/share'
      fullPath: '/sheet/$kind/$id/share'
      preLoaderRoute: typeof SheetKindIdShareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  ChangelogRoute: ChangelogRoute,
  EncounterRoute: EncounterRoute,
  GamesRoute: GamesRoute,
  CrawlersIdRoute: CrawlersIdRoute,
  CrawlersNewRoute: CrawlersNewRoute,
  DashboardIdRoute: DashboardIdRoute,
  MechsIdRoute: MechsIdRoute,
  MechsNewRoute: MechsNewRoute,
  MediatorGameIdRoute: MediatorGameIdRoute,
  PilotsIdRoute: PilotsIdRoute,
  PilotsNewRoute: PilotsNewRoute,
  SIdRoute: SIdRoute,
  SheetKindIdRoute: SheetKindIdRoute,
  MechsPatternsIndexRoute: MechsPatternsIndexRoute,
  SheetKindIdShareRoute: SheetKindIdShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
