#!/usr/bin/env bash
# smoke-production — does every production surface actually answer?
#
#   bash tools/smoke-production.sh
#
# Run by `.github/workflows/deploy-cloudflare.yml` after each deploy and by
# `.github/workflows/e2e-nightly.yml` on its daily schedule, so one list covers
# both "did what we just shipped come up" and "did something drift since". Reads
# nothing from the repo and needs no credentials — only curl and open egress.
# Exits 1 if any check fails, after running all of them.
set -euo pipefail

fail=0

# Status code of a GET, following no redirects.
check() {
  local url="$1" want="$2" label="$3"
  local got
  # On a transport failure curl still writes `000` through -w, so the status is
  # taken as-is; appending a fallback would report `000000`.
  got=$(curl -sS -o /dev/null -w '%{http_code}' --max-time 20 "$url") || true
  got=${got:-000}
  if [ "$got" = "$want" ]; then
    echo "  ok   $label ($got)"
  else
    echo "  FAIL $label — wanted $want, got $got" >&2
    fail=1
  fi
}

# A header the browser never receives is a header that does not exist, and
# `_headers` is not a promise that it arrives: Cloudflare does not apply
# `_headers` to responses generated by Worker code. Whether the CSP survives is
# a property of the platform, so it is asserted against production rather than
# read from config.
# An optional fourth argument is a fixed string the header's value must contain.
check_header() {
  local url="$1" header="$2" label="$3" want="${4:-}"
  # Captured first rather than piped: `grep -q` exits at the first match, and
  # under `pipefail` the SIGPIPE that gives curl would read as a failure.
  local headers line
  headers=$(curl -sSI --max-time 20 "$url" 2>/dev/null) || true
  line=$(printf '%s\n' "$headers" | grep -i "^${header}:" || true)
  if [ -z "$line" ]; then
    echo "  FAIL $label — no '${header}' in response headers" >&2
    fail=1
  elif [ -n "$want" ] && ! printf '%s' "$line" | grep -F "$want" >/dev/null; then
    echo "  FAIL $label — '${header}' does not contain '${want}'" >&2
    fail=1
  else
    echo "  ok   $label"
  fi
}

# A header value must NOT contain a fixed string; an absent header passes.
check_header_lacks() {
  local url="$1" header="$2" label="$3" unwanted="$4"
  local headers line
  headers=$(curl -sSI --max-time 20 "$url" 2>/dev/null) || true
  line=$(printf '%s\n' "$headers" | grep -i "^${header}:" || true)
  if printf '%s' "$line" | grep -F "$unwanted" >/dev/null; then
    echo "  FAIL $label — '${header}' contains '${unwanted}'" >&2
    fail=1
  else
    echo "  ok   $label"
  fi
}

# The PRODUCTION hostnames, not workers.dev: a broken route binding, a missing
# DNS record or a custom domain detached from its Worker all pass a workers.dev
# check while production is down.
check https://salvageunion.io/ 200 "srd home"
check https://salvageunion.io/nope-does-not-exist/ 404 "srd 404"
check https://www.salvageunion.io/ 301 "srd www redirect"
# srd's www attachment SERVES the site if the Redirect Rule is absent, quietly
# standing up a second origin; only an explicit 301 assertion tells them apart.
# itun's is checked for the same reason.
check https://www.intheunionnow.com/ 301 "itun www redirect"
check https://intheunionnow.com/ 200 "itun shell"
# Plain http must never be served. Always Use HTTPS is a zone toggle, not repo
# config (ADR-033, "Configuration outside the repo"); without it every hostname
# answers http with 200 and HSTS never reaches a first-time visitor.
check http://salvageunion.io/ 301 "srd http redirect"
check http://www.salvageunion.io/ 301 "srd www http redirect"
check http://intheunionnow.com/ 301 "itun http redirect"
check http://www.intheunionnow.com/ 301 "itun www http redirect"
check http://assets.salvageunion.io/robots.txt 301 "artwork http redirect"
# The CSP must also admit Sentry's EU ingest host, or every event is blocked in
# the browser while the project looks quiet (tools/check-observability.ts pins
# the same host in the repo's CSP sources).
check_header https://salvageunion.io/ content-security-policy "srd CSP reaches the browser and admits Sentry" ingest.de.sentry.io
check_header https://salvageunion.io/ strict-transport-security "srd HSTS reaches the browser"
check_header https://intheunionnow.com/ content-security-policy "itun CSP reaches the browser and admits Sentry" ingest.de.sentry.io
check_header https://intheunionnow.com/ strict-transport-security "itun HSTS reaches the browser"
# itun runs in single-page-application mode, so only its Worker keeps a missing
# chunk from #759, where a missing hashed chunk answered `200 text/html` and the
# `immutable` header pinned that HTML into the HTTP cache for a year. curl sends
# no `Sec-Fetch-Mode: navigate`, so these two reach the Worker exactly as a
# module import and an unfurl bot do.
check https://intheunionnow.com/assets/index-DEADBEEF.js 404 "itun rotated chunk 404 (#759)"
check https://intheunionnow.com/p/pilot/smoke 200 "itun client route without a navigation"
# `_headers` matches by path, not status, so its `/assets/*` rule would mark a
# missing chunk's 404 `immutable` and a client that asks before a deploy
# finishes would keep the 404 for a year. On both sites a Worker answers every
# miss with `no-store` instead, where `_headers` does not reach
# (apps/srd/src/worker/index.ts, apps/itun/src/worker/index.ts).
check_header_lacks https://salvageunion.io/assets/index-DEADBEEF.js cache-control "srd rotated chunk 404 is not immutable" immutable
check_header_lacks https://intheunionnow.com/assets/index-DEADBEEF.js cache-control "itun rotated chunk 404 is not immutable" immutable
# A derivative, not the master: entity cards ask for `-440`/`-880` first. It
# reaches Cloudflare Images only once the baked `-440`/`-880` objects are gone
# from su-lp-assets; while one is stored, the Worker serves that copy.
check https://assets.salvageunion.io/chassis/mule-440.webp 200 "artwork derivative"

# BODY, not status: Cloudflare's zone-level managed robots.txt also answers 200
# and carries no `Disallow`, so a status check would pass on exactly the
# regression this exists to catch — the licensed-artwork origin opening up to
# every crawler.
robots=$(curl -fsS --max-time 15 https://assets.salvageunion.io/robots.txt || true)
if printf '%s' "$robots" | grep -q '^Disallow: /$'; then
  echo "  ok   artwork origin disallows crawlers"
else
  echo "  FAIL artwork origin robots.txt has no 'Disallow: /'" >&2
  fail=1
fi

# One workers.dev check, deliberately: if the custom domains fail and this
# passes, the Worker deployed fine and the routing layer is what broke.
check https://su-srd.alxjrvs.workers.dev/ 200 "srd reachable on workers.dev"

# /health answers 200 only when both ITUN secrets are set and Discord itself
# accepted the bot token (it calls /users/@me); 503 when an ITUN secret is
# missing or the token is rejected or absent, 502 when Discord is unreachable.
# Either is otherwise invisible until the first interaction.
check https://su-discord-bot.alxjrvs.workers.dev/health 200 "bot token accepted and ITUN configured"

exit "$fail"
