#!/usr/bin/env bash
# smoke-production — does every production surface actually answer?
#
#   bash tools/smoke-production.sh
#
# Run by `.github/workflows/deploy-cloudflare.yml` after each deploy and by
# `.github/workflows/e2e-nightly.yml` on its daily schedule, so one list covers
# both "did what we just shipped come up" and "did something drift since". Reads
# nothing from the repo and needs no credentials — only curl and open egress.
# Exits 1 if any check fails, after running all of them.
set -euo pipefail

fail=0

# Status code of a GET, following no redirects.
check() {
  local url="$1" want="$2" label="$3"
  local got
  # On a transport failure curl still writes `000` through -w, so the status is
  # taken as-is; appending a fallback would report `000000`.
  got=$(curl -sS -o /dev/null -w '%{http_code}' --max-time 20 "$url") || true
  got=${got:-000}
  if [ "$got" = "$want" ]; then
    echo "  ok   $label ($got)"
  else
    echo "  FAIL $label — wanted $want, got $got" >&2
    fail=1
  fi
}

# A header the browser never receives is a header that does not exist, and
# `_headers` is not a promise that it arrives: Cloudflare does not apply
# `_headers` to responses generated by Worker code, and itun sets
# `assets.run_worker_first`. Whether the CSP survives is a property of the
# platform, so it is asserted against production rather than read from config.
check_header() {
  local url="$1" header="$2" label="$3"
  if curl -sSI --max-time 20 "$url" | grep -qi "^${header}:"; then
    echo "  ok   $label"
  else
    echo "  FAIL $label — no '${header}' in response headers" >&2
    fail=1
  fi
}

# The PRODUCTION hostnames, not workers.dev: a broken route binding, a missing
# DNS record or a custom domain detached from its Worker all pass a workers.dev
# check while production is down.
check https://salvageunion.io/ 200 "srd home"
check https://salvageunion.io/nope-does-not-exist/ 404 "srd 404"
check https://www.salvageunion.io/ 301 "srd www redirect"
# srd's www attachment SERVES the site if the Redirect Rule is absent, quietly
# standing up a second origin; only an explicit 301 assertion tells them apart.
# itun's is checked for the same reason.
check https://www.intheunionnow.com/ 301 "itun www redirect"
check https://intheunionnow.com/ 200 "itun shell"
check_header https://salvageunion.io/ content-security-policy "srd CSP reaches the browser"
check_header https://salvageunion.io/ strict-transport-security "srd HSTS reaches the browser"
check_header https://intheunionnow.com/ content-security-policy "itun CSP reaches the browser"
check_header https://intheunionnow.com/ strict-transport-security "itun HSTS reaches the browser"
# `not_found_handling` is one line of config away from reintroducing #759, where
# a missing hashed chunk answered `200 text/html` and the `immutable` header
# pinned that HTML into the HTTP cache for a year.
check https://intheunionnow.com/assets/index-DEADBEEF.js 404 "itun rotated chunk 404 (#759)"
check https://assets.salvageunion.io/chassis/mule.webp 200 "artwork"

# BODY, not status: Cloudflare's zone-level managed robots.txt also answers 200
# and carries no `Disallow`, so a status check would pass on exactly the
# regression this exists to catch — the licensed-artwork origin opening up to
# every crawler.
robots=$(curl -fsS --max-time 15 https://assets.salvageunion.io/robots.txt || true)
if printf '%s' "$robots" | grep -q '^Disallow: /$'; then
  echo "  ok   artwork origin disallows crawlers"
else
  echo "  FAIL artwork origin robots.txt has no 'Disallow: /'" >&2
  fail=1
fi

# One workers.dev check, deliberately: if the custom domains fail and this
# passes, the Worker deployed fine and the routing layer is what broke.
check https://su-srd.alxjrvs.workers.dev/ 200 "srd reachable on workers.dev"

# /health answers 200 only when Discord itself accepted the bot token (it calls
# /users/@me), 503 when the token is rejected or absent, 502 when Discord is
# unreachable. A bad token is otherwise invisible until the first interaction.
check https://su-discord-bot.alxjrvs.workers.dev/health 200 "bot token accepted by Discord"

exit "$fail"
