#!/usr/bin/env bun
/**
 * generateRegistry — codegen for the schema registration mechanism.
 *
 * Reads the single manifest (lib/schemas/registry.ts) and emits four
 * committed, human-reviewable generated files:
 *
 *   - lib/generated/modelFactoryRegistry.generated.ts
 *       dataLoaders (literal per-id `import()` calls — required for bundler
 *       code-splitting to statically analyze them) plus schemaDisplayNames.
 *       It imports NO Zod: this module is on every consumer's load path.
 *
 *   - lib/generated/zodSchemaMap.generated.ts
 *       zodSchemaMap — the entity Zod schemas keyed by schema id. Kept in its
 *       own module so the runtime loader reaches it (via lib/validateData.ts)
 *       only through a dynamic `import()` when validation is asked for, and bundlers leave the
 *       entity schemas out of the client chunks (audit PK-04).
 *
 *   - lib/generated/entityTypes.generated.ts
 *       the SURef* entity type aliases (`z.infer` of each registry schema)
 *       and the SURefEntity / SURefMetaEntity unions, whose membership comes
 *       from each entry's `entity` / `excludeFromEntityUnion` flags. Type-only: it imports the
 *       schemas with `import type`, so it adds nothing to any bundle. The
 *       lib/schemas barrel re-exports it.
 *
 *   - lib/generated/schemaRegistry.generated.ts
 *       the SchemaToEntityMap type, the LazyModel instances (inlined
 *       directly into lazyModelMap — no intermediate per-schema consts, so
 *       there's nothing here for knip to flag as an unused export), and
 *       SCHEMA_REGISTRY.
 *
 * It also injects the ~N `static X: ModelWithMetadata<...> = lazyModelMap[...]`
 * lines for the SalvageUnionReference class directly into lib/index.ts,
 * between the `// GENERATED:BEGIN` / `// GENERATED:END` marker comments
 * (which must already exist in that file). This — rather than a runtime
 * mixin/base-class trick — keeps every static property a true *own* property
 * of the class, which lib/index.test.ts depends on via
 * `Object.getOwnPropertyNames(SalvageUnionReference)`.
 *
 * Run via `bun run build:package` (before generate:json-schemas, since
 * generateJsonSchemas.ts imports zodSchemaMap from the generated file this
 * script produces).
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { toPascalCase } from '../lib/naming.js'
import type { RegistryEntry } from '../lib/schemas/registry.js'
import { registry } from '../lib/schemas/registry.js'
import { formatWithBiome, TS_FORMAT_PATH } from './formatWithBiome.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const packageRoot = join(__dirname, '..')
const generatedDir = join(packageRoot, 'lib', 'generated')
const indexPath = join(packageRoot, 'lib', 'index.ts')

const GENERATED_HEADER = `/**
 * AUTO-GENERATED by tools/generateRegistry.ts from lib/schemas/registry.ts.
 * DO NOT EDIT DIRECTLY — edit lib/schemas/registry.ts and run
 * \`bun run build:package\` to regenerate.
 */
`

// ---------------------------------------------------------------------------
// Sanity checks on the manifest
// ---------------------------------------------------------------------------

function validateRegistry(entries: RegistryEntry[]): void {
  const seenIds = new Set<string>()
  for (const entry of entries) {
    if (!/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/.test(entry.id)) {
      throw new Error(`Registry entry id "${entry.id}" must be kebab-case.`)
    }
    if (seenIds.has(entry.id)) {
      throw new Error(`Duplicate registry entry id "${entry.id}".`)
    }
    seenIds.add(entry.id)
    if (entry.entity === false && entry.excludeFromEntityUnion) {
      throw new Error(
        `Registry entry "${entry.id}" sets both entity: false and excludeFromEntityUnion — a ` +
          'non-entity schema is in neither union already, so the flag would mean nothing.'
      )
    }
    if (!/^SURef[A-Z]\w*$/.test(entry.typeName)) {
      throw new Error(`Registry entry "${entry.id}" typeName must be SURef-prefixed PascalCase.`)
    }
  }
}

// ---------------------------------------------------------------------------
// lib/generated/entityTypes.generated.ts
// ---------------------------------------------------------------------------

/** Registry entries in the SURefMetaEntity union: every entity schema. */
function metaEntityMembers(entries: RegistryEntry[]): RegistryEntry[] {
  return entries.filter((e) => e.entity !== false)
}

/** Registry entries in the narrower SURefEntity union: entities that are not rules metadata. */
function entityMembers(entries: RegistryEntry[]): RegistryEntry[] {
  return metaEntityMembers(entries).filter((e) => !e.excludeFromEntityUnion)
}

function generateEntityTypes(entries: RegistryEntry[]): string {
  const zodImports = entries.map((e) => `  ${e.zodExportName},`).join('\n')
  const aliases = entries
    .map((e) => `export type ${e.typeName} = z.infer<typeof ${e.zodExportName}>`)
    .join('\n')
  const union = (members: RegistryEntry[]) => members.map((e) => `  | ${e.typeName}`).join('\n')

  return (
    GENERATED_HEADER +
    `import type { z } from '../zod.js'
import type {
${zodImports}
} from '../schemas/entities.js'

// One alias per registry entry: the entity type is the schema's inferred type.
${aliases}

/** Every reference entity (registry entries without \`excludeFromEntityUnion\` or \`entity: false\`). */
export type SURefEntity =
${union(entityMembers(entries))}

/** SURefEntity plus the rules-metadata schemas (registry entries with \`excludeFromEntityUnion\`). */
export type SURefMetaEntity =
${union(metaEntityMembers(entries))}
`
  )
}

// ---------------------------------------------------------------------------
// lib/generated/modelFactoryRegistry.generated.ts
// ---------------------------------------------------------------------------

function generateModelFactoryRegistry(entries: RegistryEntry[]): string {
  const dataLoaders = entries
    .map(
      (e) =>
        `  '${e.id}': () => import('../../data/${e.id}.json').then((m) => m.default as unknown[]),`
    )
    .join('\n')

  const schemaDisplayNames = entries
    .map(
      (e) =>
        `  '${e.id}': { singular: ${JSON.stringify(e.singular)}, plural: ${JSON.stringify(e.plural)} },`
    )
    .join('\n')

  return (
    GENERATED_HEADER +
    `// No Zod import here, on purpose: this module is on every consumer's load
// path, and the entity schemas live in zodSchemaMap.generated.ts so that
// only a validating load pulls them in (see ModelFactory.loadSchemas).

// ---------------------------------------------------------------------------
// Lazy loader registries — no JSON is imported at module scope. Keys must be
// static string literals (not computed from the manifest at runtime) so
// bundlers can statically analyze and code-split each dynamic import().
// ---------------------------------------------------------------------------

export const dataLoaders: Record<string, () => Promise<unknown[]>> = {
${dataLoaders}
}

/**
 * Schema display name mappings
 */
export const schemaDisplayNames: Record<string, { singular: string; plural: string }> = {
${schemaDisplayNames}
}
`
  )
}

// ---------------------------------------------------------------------------
// lib/generated/zodSchemaMap.generated.ts
// ---------------------------------------------------------------------------

function generateZodSchemaMap(entries: RegistryEntry[]): string {
  const zodImports = entries.map((e) => `  ${e.zodExportName},`).join('\n')
  const zodSchemaMap = entries.map((e) => `  '${e.id}': ${e.zodExportName},`).join('\n')

  return (
    GENERATED_HEADER +
    `import type { z } from '../zod.js'
import {
${zodImports}
} from '../schemas/index.js'

/**
 * Zod schema map — the entity schemas keyed by schema id.
 *
 * The \`schemas\` data check (tools/validate.ts) and \`generate:json-schemas\`
 * import this directly, so data is validated against the exact schemas the runtime would
 * use rather than a parallel literal that could drift. At runtime only
 * \`lib/validateData.ts\` imports it, and ModelFactory reaches that module
 * through a dynamic \`import()\` when a caller passes \`{ validate: true }\` to
 * \`preload()\` — never statically, or every client bundle would carry the
 * schemas again.
 */
export const zodSchemaMap: Record<string, z.ZodType<unknown>> = {
${zodSchemaMap}
}
`
  )
}

// ---------------------------------------------------------------------------
// lib/generated/schemaRegistry.generated.ts
// ---------------------------------------------------------------------------

function generateSchemaRegistry(entries: RegistryEntry[]): string {
  const typeImports = entries.map((e) => `  ${e.typeName},`).join('\n')

  const schemaToEntityMap = entries.map((e) => `  '${e.id}': ${e.typeName}`).join('\n')

  const lazyModelMapEntries = entries
    .map(
      (e) =>
        `  '${e.id}': new LazyModel<SchemaToEntityMap['${e.id}']>(\n` +
        `    '${e.id}',\n` +
        `    '${toPascalCase(e.id)}',\n` +
        `    ${JSON.stringify(e.singular)}\n` +
        `  ),`
    )
    .join('\n')

  const schemaRegistryEntries = entries
    .map((e) => {
      const entitySuffix = e.entity === false ? `, entity: false as const` : ''
      return `  '${e.id}': { model: '${toPascalCase(e.id)}', display: ${JSON.stringify(e.singular)}${entitySuffix} },`
    })
    .join('\n')

  return (
    GENERATED_HEADER +
    `import { LazyModel } from '../LazyModel.js'
import type {
${typeImports}
} from '../schemas/index.js'

// Type mapping from schema names to entity types (includes entity schemas and meta schemas)
export type SchemaToEntityMap = {
${schemaToEntityMap}
}

// Type for entity schema names (includes entity schemas and meta schemas, excludes non-entity schemas)
export type EntitySchemaName = keyof SchemaToEntityMap

/**
 * Map from schema ID to its LazyModel instance — used by preload() to
 * install backing models. Each entry is directly \`LazyModel<SchemaToEntityMap[K]>\`
 * (a homomorphic mapped type), so no per-entry cast is needed and a generic
 * indexed access \`lazyModelMap[schemaName]\` simplifies to
 * \`LazyModel<SchemaToEntityMap[T]>\`.
 */
export const lazyModelMap: {
  readonly [K in keyof SchemaToEntityMap]: LazyModel<SchemaToEntityMap[K]>
} = {
${lazyModelMapEntries}
}

// Registry mapping every schema name to its model key and display name.
// Set \`entity: false\` for non-entity metadata schemas (excluded from EntitySchemaNames).
export const SCHEMA_REGISTRY = {
${schemaRegistryEntries}
} as const satisfies Record<
  keyof SchemaToEntityMap,
  { model: string; display: string; entity?: boolean }
>
`
  )
}

// ---------------------------------------------------------------------------
// lib/index.ts marker injection
// ---------------------------------------------------------------------------

const BEGIN_MARKER = '  // GENERATED:BEGIN — see tools/generateRegistry.ts'
const END_MARKER = '  // GENERATED:END'

function generateStaticAccessorsBlock(entries: RegistryEntry[]): string {
  const lines = entries.map((e) => {
    // Dot access when the schema id is a valid identifier (Biome's
    // lint/complexity/useLiteralKeys); bracket access for hyphenated ids.
    const access = /^[A-Za-z_$][\w$]*$/.test(e.id)
      ? `lazyModelMap.${e.id}`
      : `lazyModelMap['${e.id}']`
    return `  static ${toPascalCase(e.id)}: ModelWithMetadata<SchemaToEntityMap['${e.id}']> = ${access}`
  })
  return [BEGIN_MARKER, ...lines, END_MARKER].join('\n')
}

function injectStaticAccessors(indexSource: string, entries: RegistryEntry[]): string {
  const beginIdx = indexSource.indexOf(BEGIN_MARKER)
  const endIdx = indexSource.indexOf(END_MARKER)
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    throw new Error(
      'lib/index.ts is missing the GENERATED:BEGIN / GENERATED:END marker comments inside ' +
        'the SalvageUnionReference class body. Add them once by hand; generateRegistry.ts ' +
        'only replaces the text between them.'
    )
  }
  const before = indexSource.slice(0, beginIdx)
  const after = indexSource.slice(endIdx + END_MARKER.length)
  return before + generateStaticAccessorsBlock(entries) + after
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  validateRegistry(registry)

  mkdirSync(generatedDir, { recursive: true })

  const modelFactoryOut = join(generatedDir, 'modelFactoryRegistry.generated.ts')
  const schemaRegistryOut = join(generatedDir, 'schemaRegistry.generated.ts')
  const zodSchemaMapOut = join(generatedDir, 'zodSchemaMap.generated.ts')
  const entityTypesOut = join(generatedDir, 'entityTypes.generated.ts')

  console.log('Generating registry files from lib/schemas/registry.ts...\n')

  // lib/generated/** is biome-ignored (same treatment as routeTree.gen.ts) so
  // it's never a format:check/lint requirement, but running it through the
  // formatter anyway keeps the committed, human-reviewable output pleasant to
  // review. Because Biome would return an ignored path untouched, these go
  // through the synthetic TS_FORMAT_PATH rather than their own paths.
  const formatGenerated = (source: string) => formatWithBiome(source, TS_FORMAT_PATH)

  writeFileSync(modelFactoryOut, formatGenerated(generateModelFactoryRegistry(registry)))
  console.log('✓ Generated lib/generated/modelFactoryRegistry.generated.ts')

  writeFileSync(zodSchemaMapOut, formatGenerated(generateZodSchemaMap(registry)))
  console.log('✓ Generated lib/generated/zodSchemaMap.generated.ts')

  writeFileSync(entityTypesOut, formatGenerated(generateEntityTypes(registry)))
  console.log('✓ Generated lib/generated/entityTypes.generated.ts')

  writeFileSync(schemaRegistryOut, formatGenerated(generateSchemaRegistry(registry)))
  console.log('✓ Generated lib/generated/schemaRegistry.generated.ts')

  const indexSource = readFileSync(indexPath, 'utf-8')
  const injected = injectStaticAccessors(indexSource, registry)

  // lib/index.ts is hand-written (only the marker region is generated), and is
  // NOT biome-ignored, so format the whole file — under its own path — to keep
  // it format:check-clean and the drift check idempotent.
  const formatted = formatWithBiome(injected, indexPath)
  writeFileSync(indexPath, formatted)
  console.log('✓ Injected static accessors into lib/index.ts')

  console.log(`\n✓ Registry generation complete (${registry.length} schemas).`)
}

if (import.meta.main) await main()
